package dev.wildware.udea.codegen.protocol

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import dev.wildware.udea.codegen.GeneratedNames

/**
 * Emits the module's `…NetProtocol` object: the `protoHash` as a compile-time constant.
 *
 * The constant exists so that the framing layer can put the hash in byte 0 of every packet
 * without reading a file, parsing anything or allocating at run time — spec 3.2 asks for a
 * `u16 protoHash`, and a `const val` is the only form of it a packet header can afford.
 *
 * One object per module rather than one for the whole build, because each module's KSP run
 * only sees its own components; the Udea Gradle plugin merges the locks and is what makes the
 * game's own module's hash the authoritative one. The module name is carried in the class
 * name rather than in the package, so two modules' objects can never collide.
 */
internal object NetProtocolEmitter {

    fun emit(moduleName: String, lock: NetProtocolLock): FileSpec {
        val className = GeneratedNames.netProtocol(moduleName)
        return FileSpec.builder(className.packageName, className.simpleName)
            .addFileComment(
                "Generated by udea-codegen from %L.\nDo not edit.",
                ProtocolLock.FILE_NAME,
            )
            .addType(
                TypeSpec.objectBuilder(className.simpleName)
                    .addModifiers(KModifier.PUBLIC)
                    .addKdoc(
                        "The wire protocol `%L` was built against.\n\n" +
                            "[HASH] is the `u16` a peer puts in byte 0 of every packet and " +
                            "compares on connect: two builds whose components, field order or " +
                            "field widths differ have different hashes, so they refuse to speak " +
                            "rather than desync later. It is a compile-time constant because a " +
                            "packet header cannot afford to look anything up.\n\n" +
                            "Regenerated from `%L`, which is the reviewed source of truth.\n",
                        moduleName,
                        ProtocolLock.FILE_NAME,
                    )
                    .addProperty(
                        PropertySpec.builder("HASH", INT, KModifier.PUBLIC, KModifier.CONST)
                            .addKdoc("`u16` over the canonical protocol content.")
                            .initializer("0x%L", "%04x".format(lock.protoHash))
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder("LOCK_FORMAT", INT, KModifier.PUBLIC, KModifier.CONST)
                            .addKdoc("Format version of the lock file [HASH] was computed from.")
                            .initializer("%L", lock.formatVersion)
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder("COMPONENT_COUNT", INT, KModifier.PUBLIC, KModifier.CONST)
                            .addKdoc("How many `@Replicated` components this module contributes.")
                            .initializer("%L", lock.components.size)
                            .build(),
                    )
                    .build(),
            )
            .build()
    }
}
