package dev.wildware.udea.codegen.protocol

/** One field of a locked component: its bit index, its name and its declared wire width. */
internal data class LockedField(val index: Int, val name: String, val wire: String)

/** One component in the wire contract: its id, its name and its ordered fields. */
internal data class LockedComponent(
    val id: Int,
    val qualifiedName: String,
    val fields: List<LockedField>,
)

/** A parsed or freshly built `net-protocol.lock`. */
internal data class NetProtocolLock(
    val formatVersion: Int,
    /** `u16` over the canonical content; byte 0 of every packet (spec 3.2). */
    val protoHash: Int,
    /** In ascending id order, which is also ascending name order. */
    val components: List<LockedComponent>,
)

/**
 * The checked-in wire contract: component ids, field order and field widths, plus the `u16`
 * `protoHash` a packet header carries so two peers can refuse to speak at all rather than
 * desync in the fourth minute.
 *
 * The file is deliberately a **human-readable text format**, not JSON and not a binary blob.
 * Its whole purpose is to be diffed in review: the thing it protects against is a wire-format
 * change nobody noticed, and a diff nobody can read protects against nothing.
 *
 * Everything here is a pure function of its input. That is what the determinism requirement
 * actually reduces to: the same components must produce byte-identical text no matter what
 * order the build evaluated projects in, what machine ran it, or what time it was.
 */
internal object ProtocolLock {

    /** Bumped when the *file format* changes, which is itself a protocol change. */
    const val FORMAT_VERSION: Int = 1

    /** The name the file is checked in under, at the repository root. */
    const val FILE_NAME: String = "net-protocol.lock"

    private const val FORMAT_KEY = "lockFormat"
    private const val HASH_KEY = "protoHash"
    private const val COMPONENT_KEY = "component"
    private const val FIELD_KEY = "field"

    /**
     * The header, which explains what the file is to whoever opens the diff.
     *
     * Comment lines are excluded from [hash], so rewording this does not move the protocol —
     * which is the same reason a KDoc change on a component must not move it.
     */
    private val HEADER: List<String> = listOf(
        "# udea net-protocol.lock — THE WIRE CONTRACT.",
        "#",
        "# Component ids, field order and field widths are what a running server and a",
        "# connected client agree on. Changing anything below breaks every client already",
        "# speaking this protocol and every recorded replay. Regenerate deliberately with",
        "# `gradlew udeaWriteProtocolLock` and review the diff; `udeaCheckProtocolLock` fails",
        "# the build when the generated output and this file disagree.",
        "#",
        "# Ids are assigned from the sorted list of fully-qualified component names, so",
        "# inserting a component renumbers its successors. protoHash is a u16 over the",
        "# non-comment content below and is carried in byte 0 of every packet.",
        "#",
        "# Generated by udea-codegen. Do not edit by hand.",
    )

    /** The lock for [components], with [protoHash] computed over the canonical content. */
    fun build(components: List<LockedComponent>): NetProtocolLock {
        val ordered = components.sortedBy(LockedComponent::id)
        return NetProtocolLock(
            formatVersion = FORMAT_VERSION,
            protoHash = hash(canonicalBody(ordered)),
            components = ordered,
        )
    }

    /** The file text for [lock]: header comments, then the canonical body with the hash. */
    fun render(lock: NetProtocolLock): String = buildString {
        for (line in HEADER) appendLine(line)
        appendLine("$FORMAT_KEY ${lock.formatVersion}")
        appendLine("$HASH_KEY ${formatHash(lock.protoHash)}")
        for (component in lock.components.sortedBy(LockedComponent::id)) {
            appendLine("$COMPONENT_KEY ${component.id} ${component.qualifiedName}")
            for (field in component.fields.sortedBy(LockedField::index)) {
                appendLine("  $FIELD_KEY ${field.index} ${field.name} ${field.wire}")
            }
        }
    }

    /**
     * The content [hash] is taken over: everything but the comments and the hash line itself.
     *
     * Excluding comments is what makes the acceptance criterion true rather than accidental —
     * a KDoc or a header reword must not change the protocol, and only content that is
     * actually on the wire may.
     */
    private fun canonicalBody(components: List<LockedComponent>): String = buildString {
        appendLine("$FORMAT_KEY $FORMAT_VERSION")
        for (component in components) {
            appendLine("$COMPONENT_KEY ${component.id} ${component.qualifiedName}")
            for (field in component.fields.sortedBy(LockedField::index)) {
                appendLine("  $FIELD_KEY ${field.index} ${field.name} ${field.wire}")
            }
        }
    }

    /**
     * FNV-1a over the UTF-8 bytes of [body], folded to a `u16`.
     *
     * A `u16` because that is what fits in the packet header budget, and folding rather than
     * truncating so that every input bit reaches the result. It is a *change detector*, not a
     * security primitive: it tells two peers they were built from different protocols, and
     * `net-protocol.lock` — which is diffed, not hashed — is what tells a reviewer what
     * changed.
     */
    fun hash(body: String): Int {
        var hash = FNV_OFFSET_BASIS
        for (byte in body.toByteArray(Charsets.UTF_8)) {
            hash = hash xor (byte.toInt() and 0xFF)
            hash *= FNV_PRIME
        }
        return ((hash ushr 16) xor hash) and 0xFFFF
    }

    /** `0x1a2b` — fixed width, so a diff of two hashes lines up. */
    fun formatHash(protoHash: Int): String = "0x%04x".format(protoHash)

    /** The outcome of reading a lock file. */
    sealed interface Parse {
        data class Success(val lock: NetProtocolLock) : Parse

        /** Every problem found, so one read reports all of them rather than the first. */
        data class Failure(val problems: List<String>) : Parse
    }

    /**
     * Reads a lock file.
     *
     * This is the half that has to survive a human: the file is checked in, so it will be
     * hand-edited, merged badly and resolved by someone who picked "both sides". Every one of
     * those produces a specific message here rather than an id space that quietly hands one
     * id to two components.
     */
    fun parse(text: String): Parse {
        val problems = mutableListOf<String>()
        var formatVersion: Int? = null
        var declaredHash: Int? = null
        val components = mutableListOf<LockedComponent>()
        var fields = mutableListOf<LockedField>()

        fun flush() {
            if (components.isNotEmpty()) {
                components[components.lastIndex] = components.last().copy(fields = fields.toList())
            }
            fields = mutableListOf()
        }

        for ((number, raw) in text.lines().withIndex()) {
            val line = raw.trim()
            if (line.isEmpty() || line.startsWith("#")) continue
            val parts = line.split(' ').filter(String::isNotEmpty)
            when (parts.firstOrNull()) {
                FORMAT_KEY -> {
                    val parsed = parts.getOrNull(1)?.toIntOrNull()
                    if (parsed == null) {
                        problems += "line ${number + 1}: $FORMAT_KEY needs an integer"
                    } else {
                        formatVersion = parsed
                    }
                }

                HASH_KEY -> {
                    val parsed = parts.getOrNull(1)?.removePrefix("0x")?.toIntOrNull(16)
                    if (parsed == null) {
                        problems += "line ${number + 1}: $HASH_KEY needs a hex u16"
                    } else {
                        declaredHash = parsed
                    }
                }

                COMPONENT_KEY -> {
                    flush()
                    val id = parts.getOrNull(1)?.toIntOrNull()
                    val name = parts.getOrNull(2)
                    if (id == null || name == null) {
                        problems += "line ${number + 1}: $COMPONENT_KEY needs an id and a name"
                    } else {
                        components += LockedComponent(id, name, emptyList())
                    }
                }

                FIELD_KEY -> {
                    val index = parts.getOrNull(1)?.toIntOrNull()
                    val name = parts.getOrNull(2)
                    val wire = parts.getOrNull(3)
                    if (index == null || name == null || wire == null) {
                        problems += "line ${number + 1}: $FIELD_KEY needs an index, a name and a width"
                    } else {
                        fields += LockedField(index, name, wire)
                    }
                }

                else -> problems += "line ${number + 1}: unrecognised entry '${parts.first()}'"
            }
        }
        flush()

        if (formatVersion == null) {
            problems += "no $FORMAT_KEY line; this is not a $FILE_NAME"
        } else if (formatVersion != FORMAT_VERSION) {
            problems += "$FILE_NAME is format $formatVersion, but this build writes format " +
                "$FORMAT_VERSION; regenerate it"
        }
        problems += collisions(components)

        if (problems.isNotEmpty()) return Parse.Failure(problems)

        val recomputed = hash(canonicalBody(components.sortedBy(LockedComponent::id)))
        if (declaredHash != null && declaredHash != recomputed) {
            return Parse.Failure(
                listOf(
                    "$HASH_KEY in $FILE_NAME is ${formatHash(declaredHash)} but its content " +
                        "hashes to ${formatHash(recomputed)}; the file was edited by hand. " +
                        "Regenerate it with `gradlew udeaWriteProtocolLock`.",
                ),
            )
        }
        return Parse.Success(
            NetProtocolLock(
                formatVersion = FORMAT_VERSION,
                protoHash = recomputed,
                components = components.sortedBy(LockedComponent::id),
            ),
        )
    }

    /**
     * Two components claiming one id, or one name claiming two ids.
     *
     * Unreachable from [build], which assigns densely from sorted names — and reachable from
     * every other route into an id space: a bad merge of two branches that each added a
     * component, or a hand edit. Both names are in the message, because "id 3 collides" sends
     * the reader to grep the file and "id 3 is claimed by both A and B" does not.
     */
    private fun collisions(components: List<LockedComponent>): List<String> {
        val problems = mutableListOf<String>()
        val byId = HashMap<Int, String>(components.size)
        val byName = HashMap<String, Int>(components.size)
        for (component in components) {
            val existing = byId.put(component.id, component.qualifiedName)
            if (existing != null && existing != component.qualifiedName) {
                problems += "component type id ${component.id} is claimed by both $existing and " +
                    "${component.qualifiedName}; a component type id identifies exactly one " +
                    "component on the wire"
            }
            val previousId = byName.put(component.qualifiedName, component.id)
            if (previousId != null && previousId != component.id) {
                problems += "${component.qualifiedName} is listed under both id $previousId and " +
                    "id ${component.id}"
            }
        }
        return problems.sorted()
    }

    private const val FNV_OFFSET_BASIS = -0x7EE3623B // 0x811C9DC5
    private const val FNV_PRIME = 0x01000193
}
