package dev.wildware.udea.gradle

/**
 * The generated per-variant answer to "may this build stand the agent surface up at all".
 *
 * ## What was wrong with the hand-written constant
 *
 * `udea-agent-host`'s own `BuildFlags.AGENT_ALLOWED` is a `const val ... = true` typed into a
 * source file, and its KDoc says so out loud: the file claims to be regenerated per variant and
 * nothing regenerated it. A constant that is `true` in every build is not a release gate; it is
 * a comment. `AgentHost.startIfRequested` takes `agentAllowed` as a **parameter** defaulted to
 * that constant precisely so a game can supply an answer its own build computed, and this is
 * what computes it.
 *
 * ## Why the file is generated into the game and not into `udea-agent-host`
 *
 * The flag has to differ between a release build and a development build of **the game**, and
 * `-Pudea.release=true` is a property of the invocation that builds the game. `udea-agent-host`
 * is a library: it is compiled once, by whatever invocation needs it first, and a constant baked
 * into its jar would carry whichever variant happened to compile it. So the value belongs to the
 * game module, in the debug-only source set that is the only place that reads it, and the
 * library keeps its own constant as the default for callers that do not supply one.
 *
 * ## Deterministic
 *
 * `udeaGenerateAgentBuildFlags` is cacheable, so the rendered text is a pure function of the
 * package name and the boolean, with no timestamp and no build path in it.
 */
public object AgentBuildFlagsSource {

    /** The generated object's simple name. */
    public const val CLASS_NAME: String = "UdeaAgentBuildFlags"

    /** The generated file's name, relative to the package directory. */
    public const val FILE_NAME: String = "$CLASS_NAME.kt"

    /** Where the flag goes when a project does not name a package. */
    public const val FALLBACK_PACKAGE: String = "udea.agent"

    /**
     * A legal Kotlin package derived from a project's group and name.
     *
     * Naive concatenation does not survive contact with real projects: a project with no `group`
     * yields a package starting with a dot, and Gradle project names routinely contain hyphens,
     * which are not identifier characters. Both produce a generated file that does not compile,
     * reported against a line nobody wrote. Every segment is therefore sanitised, empty ones are
     * dropped, and a segment starting with a digit gets a leading underscore.
     *
     * A project that cares names its own package through `udeaAgent.flagsPackage`; `moba` does.
     */
    public fun defaultPackage(group: String, projectName: String): String {
        val segments = ("$group.$projectName.agent")
            .split('.')
            .map { segment -> segment.map { if (it.isLetterOrDigit() || it == '_') it else '_' }.joinToString("") }
            .filter { segment -> segment.any { it.isLetterOrDigit() } }
            .map { if (it.first().isDigit()) "_$it" else it }
        return if (segments.size < 2) FALLBACK_PACKAGE else segments.joinToString(".")
    }

    /**
     * The whole file.
     *
     * `const val`, not `val`: the branch that reads it has to be foldable, so a release build
     * carries no reachable path from the entry point to `HttpServer.create` for a shrinker to
     * decide to keep.
     *
     * @param packageName package to declare, e.g. `dev.wildware.moba.agent`.
     * @param agentAllowed `false` for a release build.
     */
    public fun render(packageName: String, agentAllowed: Boolean): String {
        require(packageName.isNotBlank()) { "the generated flags need a package" }
        return """
            |package $packageName
            |
            |/**
            | * Whether THIS build of the game may stand the agent surface up.
            | *
            | * Generated by `udeaGenerateAgentBuildFlags` (`udea-gradle`). Do not edit: the file is
            | * rewritten on every build, and `-Pudea.release=true` makes [AGENT_ALLOWED] false.
            | *
            | * It is passed to `AgentHost.startIfRequested(agentAllowed = ...)`, which is the
            | * parameter that exists so a game can answer this for itself rather than inheriting
            | * `udea-agent-host`'s library-wide default.
            | */
            |public object $CLASS_NAME {
            |
            |    /** `false` in a release build. `-Dudea.agent.port` is then ignored. */
            |    public const val AGENT_ALLOWED: Boolean = $agentAllowed
            |}
            |
        """.trimMargin()
    }
}
