package dev.wildware.udea.codegen.registry

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.joinToCode
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STAR
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import dev.wildware.udea.codegen.AnnotationNames
import dev.wildware.udea.codegen.CoreNames
import dev.wildware.udea.codegen.agent.AgentNames

/**
 * Emits a module's `<Module>ModuleRegistry` and a launcher's `<Module>UdeaRegistry` (issue #202).
 *
 * **This is what replaced `ServiceLoader`.** Each module used to emit one index class per service
 * plus a `META-INF/services` line, and every consumer walked the classpath for them at run time.
 * That cannot run on Kotlin/Wasm or Kotlin/Native, and its failure mode was silence: a service
 * file that was not on the classpath was a module that was not there, with a green build.
 *
 * What replaces it is two objects and no resource:
 *
 * - the **module registry** lists what one module contributes, by implementing one [Facet]
 *   interface per kind, each naming its members statically - so resolution costs a class-load and
 *   no reflection, and R8 keeps every member because it is genuinely referenced;
 * - the **launcher registry** names the module registries of everything on a launcher's runtime
 *   classpath, as static references. A module the build says is there and whose registry is not
 *   is a compile error, and the processor reports it by name before the compiler gets to it.
 *
 * Both are `object`s. The index classes were classes only because `ServiceLoader` constructs a
 * provider through a public no-arg constructor; nothing constructs these.
 *
 * Every name is a pure function of the module name. Nothing here reads a clock.
 */
internal object RegistryEmitter {

    /** The `Replicator<*>` list a `NetModule` exposes. */
    val REPLICATORS: Member = Member(
        propertyName = "replicators",
        elementType = CoreNames.REPLICATOR.parameterizedBy(STAR),
        kdoc = "Every `Replicator` generated for this module, in ascending component type id order.",
    )

    /** The `AgentToolDef<*>` list a `ToolModule` exposes. */
    val TOOLS: Member = Member(
        propertyName = "tools",
        elementType = AgentNames.AGENT_TOOL_DEF.parameterizedBy(STAR),
        kdoc = "Every `@AgentTool` generated for this module, in ascending tool name order.",
    )

    /** The `AgentStateSource<*>` list a `StateModule` exposes. */
    val STATES: Member = Member(
        propertyName = "states",
        elementType = AgentNames.AGENT_STATE_SOURCE.parameterizedBy(STAR),
        kdoc = "Every `@AgentState` source generated for this module, by declaring type name.",
    )

    /** The `LevelComponent<*>` list a `LevelComponentModule` exposes (issue #191). */
    val LEVEL_COMPONENTS: Member = Member(
        propertyName = "components",
        elementType = CoreNames.LEVEL_COMPONENT.parameterizedBy(STAR),
        kdoc = "Every `@Serializable` Fleks component this module declares, in ascending qualified-name order.",
    )

    /** The one list property a facet interface declares. */
    data class Member(
        val propertyName: String,
        val elementType: TypeName,
        val kdoc: String,
    )

    /**
     * One kind of contribution: the interface the registry implements for it, and its members.
     *
     * @param elements the declarations to list, already in the order they should appear.
     */
    data class Facet(
        val service: ClassName,
        val member: Member,
        val elements: List<CodeBlock>,
    )

    /**
     * `object <Module>ModuleRegistry : ModuleRegistry, <facets…>`.
     *
     * @param facets in the order they should be declared; a module that contributes nothing
     *   passes none, and still gets a registry a launcher can name.
     */
    fun module(
        index: ClassName,
        moduleName: String,
        facets: List<Facet>,
        handleComponents: List<ClassName> = emptyList(),
    ): FileSpec =
        FileSpec.builder(index.packageName, index.simpleName)
            .addFileComment("Generated by udea-codegen for module %L.\nDo not edit.", moduleName)
            .addType(
                TypeSpec.objectBuilder(index.simpleName)
                    .addModifiers(KModifier.PUBLIC)
                    .apply { if (handleComponents.isNotEmpty()) addAnnotation(handleIndex(handleComponents)) }
                    .addSuperinterface(CoreNames.MODULE_REGISTRY)
                    .apply { facets.forEach { addSuperinterface(it.service) } }
                    .addKdoc(
                        "Module %L's registry: what it contributes, one facet interface per kind.\n\n" +
                            "Every member below is named statically, so resolution costs a class-load " +
                            "and no reflection, and R8 keeps them because they are genuinely referenced.\n",
                        moduleName,
                    )
                    .addProperty(
                        PropertySpec.builder("moduleName", STRING, KModifier.OVERRIDE)
                            .addKdoc("The Gradle module this registry was generated for.")
                            .initializer("%S", moduleName)
                            .build(),
                    )
                    .apply {
                        for (facet in facets) {
                            addProperty(
                                PropertySpec.builder(
                                    facet.member.propertyName,
                                    LIST.parameterizedBy(facet.member.elementType),
                                    KModifier.OVERRIDE,
                                )
                                    .addKdoc(facet.member.kdoc)
                                    .initializer(listInitializer(facet.elements))
                                    .build(),
                            )
                        }
                    }
                    .build(),
            )
            .build()

    /**
     * `object <Module>UdeaRegistry : UdeaRegistry`, naming [modules] in ascending FQN order.
     *
     * Sorted here rather than trusted to arrive sorted, so the order is the spec's and not a
     * property of how an option string happened to be assembled.
     */
    fun launcher(index: ClassName, moduleName: String, modules: List<ClassName>): FileSpec =
        FileSpec.builder(index.packageName, index.simpleName)
            .addFileComment("Generated by udea-codegen for module %L.\nDo not edit.", moduleName)
            .addType(
                TypeSpec.objectBuilder(index.simpleName)
                    .addModifiers(KModifier.PUBLIC)
                    .addSuperinterface(CoreNames.UDEA_REGISTRY)
                    .addKdoc(
                        "Every module registry on %L's runtime classpath, as the build resolved it.\n\n" +
                            "A module the build listed and whose registry does not exist is a compile " +
                            "error here, not a module that is quietly absent at run time.\n",
                        moduleName,
                    )
                    .addProperty(
                        PropertySpec.builder(
                            "modules",
                            LIST.parameterizedBy(CoreNames.MODULE_REGISTRY),
                            KModifier.OVERRIDE,
                        )
                            .addKdoc("Every module registry, in ascending fully-qualified-name order.")
                            .initializer(
                                listInitializer(
                                    modules.sortedBy(ClassName::canonicalName).map { CodeBlock.of("%T", it) },
                                ),
                            )
                            .build(),
                    )
                    .build(),
            )
            .build()

    /**
     * `@HandleIndex(components = [A::class, B::class])`: the module's components that carry a gizmo
     * handle (issue #233), for a game's editor source set to generate gizmos from.
     *
     * An annotation rather than a facet, because what reads it is KSP in another module and not the
     * running game: it is BINARY-retained, so nothing at run time can read it, and it names no gizmo
     * type - the module stays free of `udea-editor`. Sorted by name.
     */
    private fun handleIndex(components: List<ClassName>): AnnotationSpec =
        AnnotationSpec.builder(HANDLE_INDEX)
            .addMember(
                "components = [%L]",
                components.sortedBy(ClassName::canonicalName).map { CodeBlock.of("%T::class", it) }.joinToCode(),
            )
            .build()

    private val HANDLE_INDEX: ClassName = ClassName.bestGuess(AnnotationNames.HANDLE_INDEX)

    /** `LevelComponent(Type::class, Type.serializer())`: one saveable component and its serializer. */
    fun levelComponent(type: ClassName): CodeBlock =
        CodeBlock.of("%T(%T::class, %T.serializer())", CoreNames.LEVEL_COMPONENT, type, type)

    /** `listOf(a, b, c)`, or `emptyList()`: a registry's list property, members in the order given. */
    fun listInitializer(members: List<CodeBlock>): CodeBlock {
        if (members.isEmpty()) return CodeBlock.of("emptyList()")
        return CodeBlock.builder()
            .add("listOf(")
            .apply {
                members.forEachIndexed { position, element ->
                    if (position > 0) add(", ")
                    add(element)
                }
            }
            .add(")")
            .build()
    }
}
