package dev.wildware.udea.codegen.registry

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STAR
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import dev.wildware.udea.codegen.CoreNames

/**
 * Emits one module-level index object per service, plus the `META-INF/services` line that
 * makes `ServiceLoader` find it.
 *
 * **This is what replaces the magic package.** The generator being retired listed a module's
 * serializers by writing them into an annotation on a class in `dev.wildware._serializer_`,
 * as a semicolon-joined string, under a name containing `System.currentTimeMillis()` — then
 * read them back with `Resolver.getDeclarationsFromPackage`, and, at run time, fell back to
 * an `org.reflections` classpath scan. Four mechanisms, none of them survivable by R8, none
 * of them deterministic, and the timestamped name alone is why KSP incremental processing had
 * to be disabled repository-wide.
 *
 * What replaces all four is one generated object and one text file:
 *
 * - the object is a plain `object … : <service>` listing its members as *statically named*
 *   declarations, so the JVM resolves them at class-load time with no reflection and R8 keeps
 *   them because they are genuinely referenced;
 * - the resource is the standard `META-INF/services` line, which `ServiceLoader` reads
 *   without scanning a classpath and which R8 keeps with a one-line rule.
 *
 * Both names are pure functions of the module name. Nothing here reads a clock.
 *
 * ## Generalised over the service, deliberately
 *
 * `@AgentTool`'s `ToolModule` index is the same file with a different service interface and a
 * different member list, so the mechanism is written once. The contract an index service must
 * satisfy is exactly what [emit] writes: a `moduleName: String` and one `List<…>` of the
 * declarations discovered in that module.
 */
internal object ServiceIndexEmitter {

    /** The `Replicator<*>` list a `NetModule` exposes. */
    val REPLICATORS: Member = Member(
        propertyName = "replicators",
        elementType = CoreNames.REPLICATOR.parameterizedBy(STAR),
        kdoc = "Every `Replicator` generated for this module, in ascending component type id order.",
    )

    /** The one list property an index service exposes. */
    data class Member(
        val propertyName: String,
        val elementType: TypeName,
        val kdoc: String,
    )

    /** `META-INF/services/dev.wildware.udea.net.NetModule` — where `ServiceLoader` looks. */
    fun resourcePath(service: ClassName): String = "META-INF/services/${service.canonicalName}"

    /** The single line that resource contains: the implementing object's binary name. */
    fun resourceContent(index: ClassName): String = "${index.canonicalName}\n"

    /**
     * @param service the service interface the index implements, e.g. `NetModule`.
     * @param index the object being generated, e.g. `MobaNetModule`.
     * @param moduleName the value of the generated `moduleName` property.
     * @param property the list property the service declares.
     * @param members the declarations to list, already in the order they should appear.
     */
    fun emit(
        service: ClassName,
        index: ClassName,
        moduleName: String,
        property: Member,
        members: List<ClassName>,
    ): FileSpec = FileSpec.builder(index.packageName, index.simpleName)
        .addFileComment(
            "Generated by udea-codegen for module %L.\nDo not edit.",
            moduleName,
        )
        .addType(
            TypeSpec.objectBuilder(index.simpleName)
                .addModifiers(KModifier.PUBLIC)
                .addSuperinterface(service)
                .addKdoc(
                    "This module's [%T], found through `%L`.\n\n" +
                        "Every member below is named statically, so resolution costs a " +
                        "class-load and no reflection, and R8 keeps them because they are " +
                        "genuinely referenced.\n",
                    service,
                    resourcePath(service),
                )
                .addProperty(
                    PropertySpec.builder("moduleName", STRING, KModifier.OVERRIDE)
                        .addKdoc("The Gradle module this index was generated for.")
                        .initializer("%S", moduleName)
                        .build(),
                )
                .addProperty(
                    PropertySpec.builder(
                        property.propertyName,
                        LIST.parameterizedBy(property.elementType),
                        KModifier.OVERRIDE,
                    )
                        .addKdoc(property.kdoc)
                        .initializer(listInitializer(members))
                        .build(),
                )
                .build(),
        )
        .build()

    private fun listInitializer(members: List<ClassName>): CodeBlock {
        if (members.isEmpty()) return CodeBlock.of("emptyList()")
        return CodeBlock.builder()
            .add("listOf(")
            .apply {
                members.forEachIndexed { position, element ->
                    if (position > 0) add(", ")
                    add("%T", element)
                }
            }
            .add(")")
            .build()
    }
}
