package dev.wildware.udea.codegen.protocol

import dev.wildware.udea.codegen.ModuleRoot
import dev.wildware.udea.generated.CodegenFixturesNetProtocol
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The half of the drift check that a Gradle task cannot do.
 *
 * `net-protocol.lock` is checked into this module's root, and `udeaCheckProtocolLock` — from
 * `build-logic`, so that it is the same task for every module that emits a protocol — fails
 * on `check` when the generated protocol stops matching it. That task does the text
 * comparison and prints the first differing line.
 *
 * What it cannot do is read the file *as a lock*, because it is a Gradle task and the parser
 * lives here. So this is where the reviewed file is proved to be a lock and not merely
 * matching bytes: it parses, and the `protoHash` a reviewer signed off is the same u16 the
 * generated `CodegenFixturesNetProtocol.HASH` puts in byte 0 of every packet. Before this,
 * `ProtocolLock.parse` had no caller outside its own unit test, so every collision,
 * format-version and hand-edit message it produces was unreachable from a build.
 *
 * ## The scope of this lock, and why it is one file per module
 *
 * The lock's unit is **one file per module** — `udea/<Module>-net-protocol.lock` in the
 * generated resources, `net-protocol.lock` in the module root — because a KSP run only ever
 * sees one Gradle module and cannot write a file about components it has not been shown. The
 * *id space* is nevertheless whole-project: each module's ids come from
 * `udea.projectComponents`, which the build reads from the reviewed `net-components.lock` in
 * the repository root and which the processor now *requires* of any module that emits a lock
 * at all. So the project's protocol is the ordered union of the per-module locks, no two of
 * them can describe the same component type id, and each is independently reviewable — which
 * a single merged file, regenerated by whichever module happened to build last, would not be.
 */
class ProtocolLockDriftTest {

    @Test
    fun `the checked-in lock parses, and its hash is the constant packets carry`() {
        val parsed = when (val outcome = ProtocolLock.parse(checkedIn.readText())) {
            is ProtocolLock.Parse.Success -> outcome.lock
            is ProtocolLock.Parse.Failure -> fail(
                "the checked-in ${ProtocolLock.FILE_NAME} is not readable: ${outcome.problems}",
            )
        }

        assertEquals(
            CodegenFixturesNetProtocol.HASH,
            parsed.protoHash,
            "the u16 in byte 0 of every packet must be the hash of the reviewed lock, not of " +
                "something only the build has seen",
        )
        assertEquals(CodegenFixturesNetProtocol.LOCK_FORMAT, parsed.formatVersion)
        assertEquals(CodegenFixturesNetProtocol.COMPONENT_COUNT, parsed.components.size)
    }

    @Test
    fun `every component id in the reviewed lock comes from the project id space`() {
        // The lock is per module; the id space is not. A module numbering from its own symbols
        // produces a lock that is internally consistent and still collides with every other
        // module's, so the reviewed file is checked against the reviewed *registry* — the one
        // artefact that spans modules — rather than against itself.
        val registry = ModuleRoot.file("../${PROJECT_COMPONENTS_FILE}")
        assertTrue(registry.isFile, "no ${PROJECT_COMPONENTS_FILE} at ${registry.absolutePath}")
        val idSpace = registry.readText().lines()
            .map { it.substringBefore('#').trim() }
            .filter(String::isNotEmpty)

        val parsed = (ProtocolLock.parse(checkedIn.readText()) as ProtocolLock.Parse.Success).lock
        for (component in parsed.components) {
            assertEquals(
                idSpace.indexOf(component.qualifiedName),
                component.id,
                "${component.qualifiedName} is id ${component.id} in the reviewed lock but sits " +
                    "at ${idSpace.indexOf(component.qualifiedName)} in $PROJECT_COMPONENTS_FILE; " +
                    "an id that is not the component's position in the project id space is an " +
                    "id another module can also mint",
            )
        }
    }

    @Test
    fun `the header names the tasks that actually check and rewrite the file`() {
        // Deliberately literals and not `ProtocolLock.WRITE_TASK`: an assertion written against
        // the constant it is checking cannot fail. These two strings are the task names
        // `registerNetProtocolLock` registers, and `UdeaProtocolLockTest` in build-logic reads
        // this module's `ProtocolLock.kt` to hold the two ends together.
        val header = checkedIn.readText().lines().filter { it.startsWith("#") }.joinToString("\n")

        assertTrue("udeaCheckProtocolLock" in header, header)
        assertTrue("udeaWriteProtocolLock" in header, header)
        assertFalse("udea.updateProtocolLock" in header, header)
    }

    private companion object {
        /** The whole-build component id space; see `UdeaNetComponents` in `build-logic`. */
        const val PROJECT_COMPONENTS_FILE = "net-components.lock"

        val checkedIn: File get() = ModuleRoot.file(ProtocolLock.FILE_NAME)
    }
}
