package dev.wildware.udea.agent.tools

import dev.wildware.udea.agent.AgentCommand
import dev.wildware.udea.agent.AgentToolArg
import dev.wildware.udea.agent.AgentToolDef
import dev.wildware.udea.agent.ToolModule
import dev.wildware.udea.agent.assets.AssetToolModule
import dev.wildware.udea.agent.dispatch.ToolIndex
import dev.wildware.udea.diagnostics.UdeaRules
import java.io.File
import kotlin.reflect.KClass
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * The whole engine tool surface, read the way a model reads it.
 *
 * Issue #67 has two halves. The **aggregation** half is the cross-module merge and the refusal
 * of a name published twice, which no KSP round can make because a round sees one module. The
 * **description** half is the gate on what reaches the model - and it is applied at index
 * construction as well as in the processor, because a tool a *game* writes by hand never passes
 * through a KSP round at all, and a gate with a documented way round it is not a gate.
 *
 * Every engine tool is now generated, so this file's hand-written `AgentToolDef`s exist for one
 * reason only: they are the thing the runtime gate is *for*. Deleting them would leave the gate
 * with no test that could fail.
 */
class EngineToolSurfaceTest {

    @Test
    fun `the engine modules merge into one index with no name published twice`() {
        val harness = ToolsetHarness()

        val index = ToolIndex.builder()
            .let {
                EngineToolModules.wireAll(
                    it,
                    harness.worldTools,
                    harness.timeTools,
                    harness.eventTools,
                    harness.diagTools,
                )
            }
            .build()

        assertEquals(
            listOf("UdeaAgentDiag", "UdeaAgentEvents", "UdeaAgentTime", "UdeaAgentWorld"),
            index.moduleNames,
        )
        assertEquals(
            listOf(
                "diag.entity_counts",
                "diag.frame_report",
                "diag.memory",
                "diag.system_timings",
                "events.assert_event",
                "events.clear_events",
                "events.recent_events",
                "time.fast_forward",
                "time.list_snapshots",
                "time.pause",
                "time.resume",
                "time.rewind",
                "time.set_time_scale",
                "time.snapshot",
                "time.step",
                "world.describe_entity",
                "world.destroy_entity",
                "world.get_component",
                "world.list_blueprints",
                "world.list_components",
                "world.query_entities",
                "world.set_component_field",
                "world.spawn_blueprint",
            ),
            index.tools.map { it.name },
        )
    }

    /**
     * The gap `EngineToolModules` cannot close by compiling.
     *
     * Its lists are hand-written, so naming a tool object that does not exist fails the build -
     * but adding a new `@AgentTool` and *forgetting* to list it compiles perfectly and produces
     * a capability the generated manifest advertises and the index cannot serve. The generated
     * manifest resource is the other side of that, written by the same KSP pass with no chance
     * to forget, so it is what the modules are checked against.
     */
    @Test
    fun `every generated engine tool is in a module a host can register`() {
        val manifest = File("build/generated/ksp/main/resources/udea/UdeaAgent-agent-tools.json")
        assertTrue(manifest.isFile, "no generated manifest at ${manifest.absolutePath}; run kspKotlin")

        // Deliberately a regex over the document rather than a parser: this test's job is to
        // notice a *missing* name, and a JSON model in a test that has no parser to share would
        // be a second implementation of the thing being checked.
        val published = TOOL_NAME.findAll(manifest.readText()).map { it.groupValues[1] }.toSortedSet()
        // `AssetToolModule.Assets` and not `EngineToolModules.ALL` alone: the `assets.*` toolset is
        // generated by the same KSP pass and appears in the same manifest, but it is deliberately
        // not a member of `EngineToolModules`, because it names `udea-assets-compiler` types that a
        // shipped game does not have on its classpath (see `AssetToolModule`). It is still a module
        // a host can register, which is what this test is about, so it counts here.
        val registered = (EngineToolModules.ALL + AssetToolModule.Assets)
            .flatMap { module -> module.tools.map { it.name } }
            .toSortedSet()

        assertEquals(
            published,
            registered,
            "the generated manifest and EngineToolModules disagree; a tool in one and not the " +
                "other is either advertised and unreachable, or reachable and undiscoverable",
        )
    }

    @Test
    fun `two modules publishing one tool name are refused, naming both`() {
        // The check no KSP round can make: a round sees one module, so this is the first place
        // the whole classpath is visible at once.
        val harness = ToolsetHarness()
        val shadow = module(
            "ShadowModule",
            EngineToolModules.World.tools.filter { it.name == "world.query_entities" },
        )

        val failure = assertFailsWith<IllegalStateException> {
            ToolIndex.builder()
                .module(EngineToolModules.World)
                .module(shadow)
                .toolset(harness.worldTools)
                .build()
        }

        assertTrue(failure.message!!.contains("world.query_entities"), failure.message!!)
        assertTrue(failure.message!!.contains("UdeaAgentWorld"), failure.message!!)
        assertTrue(failure.message!!.contains("ShadowModule"), failure.message!!)
    }

    @Test
    fun `a hand-written tool whose description is too short is refused under UDEA0008`() {
        val thin = module(
            "ThinModule",
            listOf(HandWrittenTool("world.thin", "spawns stuff")),
        )
        val harness = ToolsetHarness()

        val failure = assertFailsWith<IllegalStateException> {
            ToolIndex.builder().module(thin).toolset(harness.worldTools).build()
        }

        assertTrue(failure.message!!.startsWith(UdeaRules.AGENT_TOOL_DESCRIPTION.id), failure.message!!)
        assertTrue(failure.message!!.contains("world.thin"), failure.message!!)
        assertTrue(
            failure.message!!.contains("when to reach for it"),
            "a rule must say what to write, not only what is wrong: ${failure.message}",
        )
    }

    @Test
    fun `a hand-written argument with no description is refused under UDEA0009`() {
        val thin = module(
            "UndescribedArgModule",
            listOf(
                HandWrittenTool(
                    "world.undescribed",
                    "Does a thing and says clearly when you would want to do it.",
                    listOf(AgentToolArg("id", "integer", "", required = true, default = null)),
                ),
            ),
        )
        val harness = ToolsetHarness()

        val failure = assertFailsWith<IllegalStateException> {
            ToolIndex.builder().module(thin).toolset(harness.worldTools).build()
        }

        assertTrue(failure.message!!.startsWith(UdeaRules.AGENT_ARG_DESCRIPTION.id), failure.message!!)
    }

    @Test
    fun `every engine description says what the tool does and when to reach for it`() {
        // Read as the model would, and asserted mechanically for the properties prose can be
        // checked for: long enough to carry an intent, and not merely the name in words.
        val all = EngineToolModules.ALL.flatMap { it.tools }

        for (tool in all) {
            assertTrue(
                tool.description.length >= UdeaRules.MIN_TOOL_DESCRIPTION,
                "${tool.name} is described in ${tool.description.length} characters",
            )
            val nameWords = tool.name.substringAfter('.').split('_').toSet()
            val descriptionWords = tool.description.lowercase()
                .split(Regex("[^a-z]+"))
                .filter { it.isNotEmpty() }
                .toSet()
            assertTrue(
                (descriptionWords - nameWords).size >= MIN_NEW_WORDS,
                "${tool.name} only restates its own name: ${tool.description}",
            )
            for (arg in tool.args) {
                assertTrue(arg.description.isNotBlank(), "${tool.name}.${arg.name} has no description")
            }
        }
    }

    @Test
    fun `every tool publishes a schema in the shape the bridge parser accepts`() {
        for (tool in EngineToolModules.ALL.flatMap { it.tools }) {
            val schema = tool.inputSchema
            assertTrue(schema.startsWith("{"), "${tool.name}: inputSchema must be an object")
            assertTrue(schema.contains("\"\$schema\":\"$SCHEMA_DIALECT\""), "${tool.name}: $schema")
            assertTrue(schema.contains("\"additionalProperties\":false"), "${tool.name}: $schema")
            for (arg in tool.args) {
                assertTrue(schema.contains("\"${arg.name}\":{"), "${tool.name} omits ${arg.name}: $schema")
            }
            // A default is folded into the description and never emitted as `default`, which is
            // what the bridge does when it builds a schema itself.
            assertTrue(!schema.contains("\"default\":"), "${tool.name} emitted a default: $schema")
            for (arg in tool.args.filter { it.default != null }) {
                assertTrue(
                    schema.contains("(default ${arg.default})"),
                    "${tool.name}.${arg.name}'s default is not in its description: $schema",
                )
            }
        }
    }

    /**
     * The `AgentContext` parameter never reaches the model.
     *
     * `time.step` declares one and takes exactly one *argument*. If the emitter published the
     * context as a property, the schema would demand something no agent can send and every call
     * would be refused by a strict client before it left the bridge.
     */
    @Test
    fun `a declared AgentContext is not published as an argument`() {
        val step = EngineToolModules.Time.tools.single { it.name == "time.step" }

        assertEquals(listOf("ticks"), step.args.map { it.name })
        assertTrue(!step.inputSchema.contains("context"), step.inputSchema)
    }

    @Test
    fun `a contextual tool refuses to run without the context it declared it needs`() {
        val harness = ToolsetHarness()
        val def = EngineToolModules.Time.tools.single { it.name == "time.step" }

        assertTrue(def is ContextualToolDef<*>, "time.step must be generated as a ContextualToolDef")

        @Suppress("UNCHECKED_CAST")
        val typed = def as AgentToolDef<TimeToolset>

        // Doing half the work would be worse than refusing: the step would never run and the
        // command would confirm anyway.
        assertFailsWith<UnsupportedOperationException> {
            typed.invoke(harness.timeTools, AgentCommand("time.step", mapOf("ticks" to "1")))
        }
    }

    private fun module(name: String, tools: List<AgentToolDef<*>>): ToolModule = object : ToolModule {
        override val moduleName: String = name
        override val tools: List<AgentToolDef<*>> = tools
    }

    /**
     * A tool written by hand rather than generated - which the contract allows a game to do, and
     * which is the only thing the runtime description gate can still catch.
     */
    private class HandWrittenTool(
        override val name: String,
        override val description: String,
        override val args: List<AgentToolArg> = emptyList(),
    ) : AgentToolDef<WorldToolset> {
        override val owner: KClass<*> = WorldToolset::class
        override val inputSchema: String = "{}"
        override fun invoke(receiver: WorldToolset, command: AgentCommand): Any? = null
    }

    private companion object {
        /**
         * Words a description must add beyond the ones already in the tool's own name.
         *
         * The token-overlap rule from issue #67, applied to prose rather than trusted: a
         * description that is the name spelled out tells the model nothing it did not have.
         */
        const val MIN_NEW_WORDS: Int = 10

        /** The dialect `udea-codegen` writes into every generated `inputSchema`. */
        const val SCHEMA_DIALECT: String = "https://json-schema.org/draft/2020-12/schema"

        /**
         * `"name": "world.query_entities"` in the generated manifest's `tools[]`.
         *
         * The dot used to be what told a *tool* name apart from a toolset's or an argument's,
         * and it stopped working the day `close` was added: the bridge publishes that command
         * unqualified for every conforming game, so `LifecycleToolset` cannot spell it
         * `lifecycle.close`, and a dot-requiring regex silently left it out of `published` -
         * a test that reported agreement because it could not see the disagreement.
         *
         * What is matched instead is the *shape of a tool entry*: a `"name"` whose very next
         * member is `"description"`. A toolset's name is followed by `"tools"` and an argument's
         * by `"type"`, so neither can be mistaken for one, and an unqualified tool name is seen.
         */
        val TOOL_NAME = Regex("\"name\"\\s*:\\s*\"([a-z][a-z0-9_.]*)\",\\s*\"description\"")
    }
}
