package dev.wildware.udea.codegen.replicator

import com.squareup.kotlinpoet.ANY
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import dev.wildware.udea.codegen.CoreNames

/**
 * Turns a [ReplicatedComponent] into the `Replicator<T>` object for it.
 *
 * **KotlinPoet, never string building.** The generator this replaces assembled Kotlin by
 * concatenating strings, so a property named `` `in` ``, a package with a keyword segment or a
 * `$` in a message all produced source that did not compile — and it found out at the next
 * task boundary, not at the symbol. Every identifier below goes through `%N` and every literal
 * string through `%S`, which is exactly the escaping that was missing.
 *
 * Emission is **total**: it cannot fail, because every question that could fail was answered
 * while [ComponentModelBuilder] built the model. There is no `try/catch` anywhere in this file.
 */
internal object ReplicatorEmitter {

    fun emit(component: ReplicatedComponent): FileSpec =
        FileSpec.builder(component.className.packageName, component.replicatorName)
            .addFileComment(
                "Generated by udea-codegen from @Replicated %L.\nDo not edit.",
                component.qualifiedName,
            )
            .addType(replicatorObject(component))
            .build()

    private fun replicatorObject(component: ReplicatedComponent): TypeSpec {
        val fields = component.fields
        val builder = TypeSpec.objectBuilder(component.replicatorName)
            .addModifiers(KModifier.PUBLIC)
            .addKdoc(kdoc(component))
            .addSuperinterface(CoreNames.REPLICATOR.parameterizedBy(component.className))

        builder.addProperty(
            PropertySpec.builder("FIELD_COUNT", INT, KModifier.PUBLIC, KModifier.CONST)
                .addKdoc("The number of `@Net` plus `@Sim` fields; the width of every mask here.")
                .initializer("%L", fields.size)
                .build(),
        )
        for (field in fields) {
            builder.addProperty(
                PropertySpec.builder(field.constant, INT, KModifier.PUBLIC, KModifier.CONST)
                    .addKdoc(
                        "Bit index of `%L` (%L).",
                        field.name,
                        if (field.net) "@Net" else "@Sim",
                    )
                    .initializer("%L", field.index)
                    .build(),
            )
        }
        builder.addProperty(
            PropertySpec.builder("TYPE_NAME", STRING, KModifier.PRIVATE, KModifier.CONST)
                .initializer("%S", component.typeName)
                .build(),
        )

        builder.addProperty(typeIdProperty(component))
        builder.addProperty(
            PropertySpec.builder("fieldNames", LIST.parameterizedBy(STRING), KModifier.OVERRIDE)
                .initializer(fieldNamesInitializer(fields))
                .build(),
        )
        builder.addProperty(
            PropertySpec.builder("netMask", CoreNames.FIELD_MASK, KModifier.OVERRIDE)
                .initializer(netMaskInitializer(component))
                .build(),
        )
        builder.addProperty(
            PropertySpec.builder("allMask", CoreNames.FIELD_MASK, KModifier.OVERRIDE)
                .initializer("%T.lowest(FIELD_COUNT)", CoreNames.MASK_OPS)
                .build(),
        )

        builder.addFunction(capture(component))
        builder.addFunction(diff(component))
        builder.addFunction(write(component))
        builder.addFunction(read(component))
        builder.addFunction(apply(component))
        builder.addFunction(getField(component))
        builder.addFunction(setField(component))
        return builder.build()
    }

    /**
     * The `typeId` override, kept as its own function because it is the one member of the
     * generated object whose *type* has already moved once: `udea-core` replaced the bare `Int`
     * with the `ComponentTypeId` value class, so a framing layer cannot transpose it with a
     * `slot` or a `fieldIndex`. The literal is still an `Int`, and `TypeIds.placeholder` masks
     * off the sign bit, which is what satisfies `ComponentTypeId`'s `raw >= 0` precondition.
     */
    private fun typeIdProperty(component: ReplicatedComponent): PropertySpec =
        PropertySpec.builder("typeId", CoreNames.COMPONENT_TYPE_ID, KModifier.OVERRIDE)
            .addKdoc(
                "Placeholder derived from the FQN. The authoritative id is assigned from\n" +
                    "`net-protocol.lock`; nothing may persist this value.",
            )
            .initializer("%T(%L)", CoreNames.COMPONENT_TYPE_ID, TypeIds.placeholder(component.qualifiedName))
            .build()

    private fun kdoc(component: ReplicatedComponent): CodeBlock {
        val doc = CodeBlock.builder()
            .add("Generated `Replicator` for [%T].\n\n", component.className)
            .add("Field indices are assigned by name, ascending — see `FieldOrder`:\n\n")
            .add("| index | field | mask |\n|---|---|---|\n")
        for (field in component.fields) {
            doc.add(
                "| %L | `%L` | %L |\n",
                field.index,
                field.name,
                if (field.net) "`@Net` — net and all" else "`@Sim` — all only",
            )
        }
        return doc.build()
    }

    private fun fieldNamesInitializer(fields: List<ReplicatedField>): CodeBlock =
        if (fields.isEmpty()) {
            CodeBlock.of("emptyList()")
        } else {
            CodeBlock.builder()
                .add("listOf(")
                .apply {
                    fields.forEachIndexed { i, field ->
                        if (i > 0) add(", ")
                        add("%S", field.name)
                    }
                }
                .add(")")
                .build()
        }

    private fun netMaskInitializer(component: ReplicatedComponent): CodeBlock {
        val net = component.netFields
        if (net.isEmpty()) return CodeBlock.of("%T.EMPTY", CoreNames.MASK_OPS)
        return CodeBlock.builder()
            .add("%T.of(", CoreNames.MASK_OPS)
            .apply {
                net.forEachIndexed { i, field ->
                    if (i > 0) add(", ")
                    add("%L", field.constant)
                }
            }
            .add(")")
            .build()
    }

    private fun capture(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        for (field in component.fields) {
            if (field.enumEntries != null) {
                body.addStatement(
                    "store.set%L(slot, %L, component.%N.ordinal)",
                    field.storage.accessor, field.constant, field.name,
                )
            } else {
                body.addStatement(
                    "store.set%L(slot, %L, component.%N)",
                    field.storage.accessor, field.constant, field.name,
                )
            }
        }
        return FunSpec.builder("capture")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("component", component.className)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slot", INT)
            .returns(UNIT)
            .addCode(body.build())
            .build()
    }

    /**
     * `diff` must agree field-for-field with `FieldStore.fieldEquals`, which `desync_report`
     * walks — so a `Float` is compared as `toRawBits()`, never with `!=`. IEEE 754 says
     * `NaN != NaN` and `0.0f == -0.0f`; the store's semantics are the stored representation and
     * say the opposite on both counts. `getFloat(a) != getFloat(b)` would make a delta encoder
     * that never converges (`NaN` resends for ever) and one that silently under-replicates a
     * sign flip through zero. `FieldStore.fieldEquals`' KDoc states this as a requirement on
     * every emitted `diff`.
     */
    private fun diff(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        if (component.fields.isEmpty()) {
            body.addStatement("return %T.EMPTY", CoreNames.MASK_OPS)
        } else {
            body.addStatement("var mask: %T = %T.EMPTY", CoreNames.FIELD_MASK, CoreNames.MASK_OPS)
            for (field in component.fields) {
                val compared = if (field.storage == FieldStorage.FLOAT) ".toRawBits()" else ""
                body.beginControlFlow(
                    "if (store.get%L(slotA, %L)%L != store.get%L(slotB, %L)%L)",
                    field.storage.accessor, field.constant, compared,
                    field.storage.accessor, field.constant, compared,
                )
                body.addStatement("mask = %T.set(mask, %L)", CoreNames.MASK_OPS, field.constant)
                body.endControlFlow()
            }
            body.addStatement("return mask")
        }
        return FunSpec.builder("diff")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slotA", INT)
            .addParameter("slotB", INT)
            .returns(CoreNames.FIELD_MASK)
            .addCode(body.build())
            .build()
    }

    private fun write(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        body.add("// An empty mask emits zero bits: no mask, no header, nothing.\n")
        body.beginControlFlow("if (%T.isEmpty(mask))", CoreNames.MASK_OPS)
        body.addStatement("return")
        body.endControlFlow()
        body.addStatement("%T.writeTo(mask, out, FIELD_COUNT)", CoreNames.MASK_OPS)
        for (field in component.fields) {
            body.beginControlFlow("if (%T.test(mask, %L))", CoreNames.MASK_OPS, field.constant)
            body.addStatement(
                "out.write%L(store.get%L(slot, %L))",
                field.storage.accessor, field.storage.accessor, field.constant,
            )
            body.endControlFlow()
        }
        return FunSpec.builder("write")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slot", INT)
            .addParameter("mask", CoreNames.FIELD_MASK)
            .addParameter("out", CoreNames.BIT_WRITER)
            .returns(UNIT)
            .addCode(body.build())
            .build()
    }

    /**
     * `read` is the **trust boundary**: it is the only entry point that puts bytes it did not
     * produce into a `FieldStore`. So an enum arrives as an unconstrained 32-bit ordinal and is
     * range-checked *here*, before the store sees it — not in `apply`, where the array index
     * would already be reading a poisoned slot and the same bad value would sit in every
     * rewind slot captured from it.
     *
     * The check names the component, the field, the offending ordinal and the valid range,
     * because the two realistic sources are a corrupt datagram and ordinary version skew
     * between two builds whose enum has a different number of constants — and a bare
     * `IndexOutOfBoundsException` from inside generated code names none of them.
     */
    private fun read(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        body.addStatement(
            "val mask: %T = %T.readFrom(src, FIELD_COUNT)",
            CoreNames.FIELD_MASK, CoreNames.MASK_OPS,
        )
        for (field in component.fields) {
            body.beginControlFlow("if (%T.test(mask, %L))", CoreNames.MASK_OPS, field.constant)
            val enum = field.enumEntries
            if (enum == null) {
                body.addStatement(
                    "store.set%L(slot, %L, src.read%L())",
                    field.storage.accessor, field.constant, field.storage.accessor,
                )
            } else {
                val local = "${field.name}Ordinal"
                body.add(
                    "// The trust boundary: this ordinal is unconstrained until checked, and a\n" +
                        "// bad one must never reach the store — the snapshot ring shares it.\n",
                )
                body.addStatement("val %N = src.read%L()", local, field.storage.accessor)
                body.addStatement(
                    "require(%N in %T.entries.indices) { TYPE_NAME + %S + %N + %S + %T.entries.size + %S }",
                    local,
                    enum,
                    ".${field.name}: ordinal ",
                    local,
                    " is not a ${display(enum)} constant (0 until ",
                    enum,
                    ")",
                )
                body.addStatement(
                    "store.set%L(slot, %L, %N)",
                    field.storage.accessor, field.constant, local,
                )
            }
            body.endControlFlow()
        }
        body.addStatement("return mask")
        return FunSpec.builder("read")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("src", CoreNames.BIT_READER)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slot", INT)
            .returns(CoreNames.FIELD_MASK)
            .addCode(body.build())
            .build()
    }

    /**
     * `apply` indexes `entries` directly, and that is safe *because* of the two writers into
     * the store: [capture] writes `.ordinal`, which is in range by construction, and [read]
     * range-checks before writing. There is no third writer, so an out-of-range ordinal can
     * never be in the slot this reads.
     */
    private fun apply(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        for (field in component.fields) {
            body.beginControlFlow("if (%T.test(mask, %L))", CoreNames.MASK_OPS, field.constant)
            if (field.enumEntries != null) {
                body.addStatement(
                    "component.%N = %T.entries[store.get%L(slot, %L)]",
                    field.name, field.enumEntries, field.storage.accessor, field.constant,
                )
            } else {
                body.addStatement(
                    "component.%N = store.get%L(slot, %L)",
                    field.name, field.storage.accessor, field.constant,
                )
            }
            body.endControlFlow()
        }
        return FunSpec.builder("apply")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slot", INT)
            .addParameter("component", component.className)
            .addParameter("mask", CoreNames.FIELD_MASK)
            .returns(UNIT)
            .addCode(body.build())
            .build()
    }

    private fun getField(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        if (component.fields.isEmpty()) {
            body.addStatement(
                "throw %T(TYPE_NAME, fieldIndex, FIELD_COUNT)",
                CoreNames.NO_SUCH_FIELD_INDEX,
            )
        } else {
            body.beginControlFlow("return when (fieldIndex)")
            for (field in component.fields) {
                body.addStatement("%L -> component.%N", field.constant, field.name)
            }
            body.addStatement(
                "else -> throw %T(TYPE_NAME, fieldIndex, FIELD_COUNT)",
                CoreNames.NO_SUCH_FIELD_INDEX,
            )
            body.endControlFlow()
        }
        return FunSpec.builder("getField")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("component", component.className)
            .addParameter("fieldIndex", INT)
            .returns(ANY.copy(nullable = true))
            .addCode(body.build())
            .build()
    }

    private fun setField(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        if (component.fields.isEmpty()) {
            body.addStatement(
                "throw %T(TYPE_NAME, fieldIndex, FIELD_COUNT)",
                CoreNames.NO_SUCH_FIELD_INDEX,
            )
        } else {
            body.beginControlFlow("when (fieldIndex)")
            for (field in component.fields) {
                body.addStatement(
                    "%L -> component.%N = value as? %T ?: throw IllegalArgumentException(" +
                        "TYPE_NAME + %S + value)",
                    field.constant,
                    field.name,
                    field.declaredType,
                    ".${field.name} expects ${display(field.declaredType)}, got ",
                )
            }
            body.addStatement(
                "else -> throw %T(TYPE_NAME, fieldIndex, FIELD_COUNT)",
                CoreNames.NO_SUCH_FIELD_INDEX,
            )
            body.endControlFlow()
        }
        return FunSpec.builder("setField")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("component", component.className)
            .addParameter("fieldIndex", INT)
            .addParameter("value", ANY.copy(nullable = true))
            .returns(UNIT)
            .addCode(body.build())
            .build()
    }

    /** How a type is spelled in a runtime error message: the simple name, not the FQN. */
    private fun display(type: TypeName): String =
        if (type is ClassName) type.simpleNames.joinToString(".") else type.toString()
}
