package dev.wildware.udea.codegen.replicator

import com.squareup.kotlinpoet.ANY
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import dev.wildware.udea.codegen.CoreNames

/**
 * Turns a [ReplicatedComponent] into the `Replicator<T>` object for it.
 *
 * **KotlinPoet, never string building.** The generator this replaces assembled Kotlin by
 * concatenating strings, so a property named `` `in` ``, a package with a keyword segment or a
 * `$` in a message all produced source that did not compile — and it found out at the next
 * task boundary, not at the symbol. Every identifier below goes through `%N` and every literal
 * string through `%S`, which is exactly the escaping that was missing.
 *
 * Emission is **total**: it cannot fail, because every question that could fail was answered
 * while [ComponentModelBuilder] built the model. There is no `try/catch` anywhere in this file.
 *
 * A component with a `@Q` field emits calls to `udea-net`'s `writeFixed`/`readFixed`, so such
 * a module needs `udea-net` on its runtime classpath. That is where the frozen contract puts
 * quantisation, and re-deriving the mapping in generated source would give the engine two
 * implementations of a wire format that must agree to the rounding mode.
 */
internal object ReplicatorEmitter {

    fun emit(component: ReplicatedComponent, typeId: Int): FileSpec =
        FileSpec.builder(component.className.packageName, component.replicatorName)
            .addFileComment(
                "Generated by udea-codegen from @Replicated %L.\nDo not edit.",
                component.qualifiedName,
            )
            .addType(replicatorObject(component, typeId))
            .build()

    private fun replicatorObject(component: ReplicatedComponent, typeId: Int): TypeSpec {
        val fields = component.fields
        val builder = TypeSpec.objectBuilder(component.replicatorName)
            .addModifiers(KModifier.PUBLIC)
            .addKdoc(kdoc(component))
            .addSuperinterface(CoreNames.REPLICATOR.parameterizedBy(component.className))

        builder.addProperty(
            PropertySpec.builder("FIELD_COUNT", INT, KModifier.PUBLIC, KModifier.CONST)
                .addKdoc("The number of `@Net` plus `@Sim` fields; the width of every mask here.")
                .initializer("%L", fields.size)
                .build(),
        )
        for (field in fields) {
            builder.addProperty(
                PropertySpec.builder(field.constant, INT, KModifier.PUBLIC, KModifier.CONST)
                    .addKdoc(
                        "Bit index of `%L` (%L).",
                        field.name,
                        if (field.net) "@Net" else "@Sim",
                    )
                    .initializer("%L", field.index)
                    .build(),
            )
        }
        builder.addProperty(
            PropertySpec.builder("TYPE_NAME", STRING, KModifier.PRIVATE, KModifier.CONST)
                .initializer("%S", component.typeName)
                .build(),
        )

        builder.addProperty(typeIdProperty(typeId))
        builder.addProperty(
            PropertySpec.builder("fieldNames", LIST.parameterizedBy(STRING), KModifier.OVERRIDE)
                .initializer(fieldNamesInitializer(fields))
                .build(),
        )
        builder.addProperty(
            PropertySpec.builder("netMask", CoreNames.FIELD_MASK, KModifier.OVERRIDE)
                .initializer(netMaskInitializer(component))
                .build(),
        )
        builder.addProperty(
            PropertySpec.builder("allMask", CoreNames.FIELD_MASK, KModifier.OVERRIDE)
                .initializer("%T.lowest(FIELD_COUNT)", CoreNames.MASK_OPS)
                .build(),
        )

        builder.addFunction(capture(component))
        builder.addFunction(diff(component))
        builder.addFunction(write(component))
        builder.addFunction(read(component))
        builder.addFunction(apply(component))
        builder.addFunction(getField(component))
        builder.addFunction(setField(component))
        return builder.build()
    }

    /**
     * The `typeId` override, kept as its own function because it is the one member of the
     * generated object whose *type* has already moved once: `udea-core` replaced the bare `Int`
     * with the `ComponentTypeId` value class, so a framing layer cannot transpose it with a
     * `slot` or a `fieldIndex`.
     *
     * The literal is an id [TypeIds.assignIds] handed out from sorted fully-qualified names,
     * which is a dense `u16` and therefore always satisfies `ComponentTypeId`'s `raw >= 0`
     * precondition. That precondition is the reason the id is not a hash: a negative literal
     * here is not a compile error and not a failed generation, it is a generated file that
     * compiles cleanly and throws from its own class initialiser the first time the game
     * touches that component.
     */
    private fun typeIdProperty(typeId: Int): PropertySpec =
        PropertySpec.builder("typeId", CoreNames.COMPONENT_TYPE_ID, KModifier.OVERRIDE)
            .addKdoc(
                "Assigned from the sorted component names pinned in `net-protocol.lock`.\n" +
                    "Changing it breaks every client already speaking this protocol.",
            )
            .initializer("%T(%L)", CoreNames.COMPONENT_TYPE_ID, typeId)
            .build()

    private fun kdoc(component: ReplicatedComponent): CodeBlock {
        val doc = CodeBlock.builder()
            .add("Generated `Replicator` for [%T].\n\n", component.className)
            .add("Field indices are assigned by name, ascending — see `FieldOrder`. A composite\n")
            .add("property is lowered to one field per component, so its name carries a dot:\n\n")
            .add("| index | field | mask | wire |\n|---|---|---|---|\n")
        for (field in component.fields) {
            doc.add(
                "| %L | `%L` | %L | %L |\n",
                field.index,
                field.name,
                if (field.net) "`@Net` — net and all" else "`@Sim` — all only",
                wireDescription(field),
            )
        }
        return doc.build()
    }

    /**
     * What the KDoc table says a field costs, and — for a quantised field — what that costs
     * in accuracy.
     *
     * The epsilon is stated per field rather than per bit width in the abstract, because it
     * depends on the range as well: 12 bits over `[-π, π]` is 0.00077 rad, and 12 bits over a
     * 2048-unit world is 0.25 units. A reader can see the trade without running anything, and
     * `GeneratedReplicatorQuantisationTest` asserts the round trip actually holds to it.
     */
    private fun wireDescription(field: ReplicatedField): String {
        val quantisation = field.quantisation ?: return "${field.storage.wireBits} bits"
        return "${quantisation.bits} bits quantised over " +
            "[${quantisation.min}, ${quantisation.max}], max error ${quantisation.epsilon}"
    }

    private fun fieldNamesInitializer(fields: List<ReplicatedField>): CodeBlock =
        if (fields.isEmpty()) {
            CodeBlock.of("emptyList()")
        } else {
            CodeBlock.builder()
                .add("listOf(")
                .apply {
                    fields.forEachIndexed { i, field ->
                        if (i > 0) add(", ")
                        add("%S", field.name)
                    }
                }
                .add(")")
                .build()
        }

    private fun netMaskInitializer(component: ReplicatedComponent): CodeBlock {
        val net = component.netFields
        if (net.isEmpty()) return CodeBlock.of("%T.EMPTY", CoreNames.MASK_OPS)
        return CodeBlock.builder()
            .add("%T.of(", CoreNames.MASK_OPS)
            .apply {
                net.forEachIndexed { i, field ->
                    if (i > 0) add(", ")
                    add("%L", field.constant)
                }
            }
            .add(")")
            .build()
    }

    private fun capture(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        for (field in component.fields) body.add(FieldIo.capture(field))
        return FunSpec.builder("capture")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("component", component.className)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slot", INT)
            .returns(UNIT)
            .addCode(body.build())
            .build()
    }

    /**
     * `diff` must agree field-for-field with `FieldStore.fieldEquals`, which `desync_report`
     * walks — so a `Float` is compared as `toRawBits()`, never with `!=`. IEEE 754 says
     * `NaN != NaN` and `0.0f == -0.0f`; the store's semantics are the stored representation and
     * say the opposite on both counts. `getFloat(a) != getFloat(b)` would make a delta encoder
     * that never converges (`NaN` resends for ever) and one that silently under-replicates a
     * sign flip through zero. `FieldStore.fieldEquals`' KDoc states this as a requirement on
     * every emitted `diff`.
     */
    private fun diff(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        if (component.fields.isEmpty()) {
            body.addStatement("return %T.EMPTY", CoreNames.MASK_OPS)
        } else {
            body.addStatement("var mask: %T = %T.EMPTY", CoreNames.FIELD_MASK, CoreNames.MASK_OPS)
            for (field in component.fields) {
                body.add("if (").add(FieldIo.differs(field)).add(") {\n").indent()
                body.addStatement("mask = %T.set(mask, %L)", CoreNames.MASK_OPS, field.constant)
                body.unindent().add("}\n")
            }
            body.addStatement("return mask")
        }
        return FunSpec.builder("diff")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slotA", INT)
            .addParameter("slotB", INT)
            .returns(CoreNames.FIELD_MASK)
            .addCode(body.build())
            .build()
    }

    private fun write(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        body.add("// An empty mask emits zero bits: no mask, no header, nothing.\n")
        body.beginControlFlow("if (%T.isEmpty(mask))", CoreNames.MASK_OPS)
        body.addStatement("return")
        body.endControlFlow()
        body.addStatement("%T.writeTo(mask, out, FIELD_COUNT)", CoreNames.MASK_OPS)
        for (field in component.fields) {
            body.beginControlFlow("if (%T.test(mask, %L))", CoreNames.MASK_OPS, field.constant)
            body.add(FieldIo.write(field))
            body.endControlFlow()
        }
        return FunSpec.builder("write")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slot", INT)
            .addParameter("mask", CoreNames.FIELD_MASK)
            .addParameter("out", CoreNames.BIT_WRITER)
            .returns(UNIT)
            .addCode(body.build())
            .build()
    }

    /**
     * `read` is the **trust boundary**: it is the only entry point that puts bytes it did not
     * produce into a `FieldStore`. Every value with a legal range is checked here, before the
     * store sees it — not in `apply`, where the array index would already be reading a
     * poisoned slot and the same bad value would sit in every rewind slot captured from it.
     */
    private fun read(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        body.addStatement(
            "val mask: %T = %T.readFrom(src, FIELD_COUNT)",
            CoreNames.FIELD_MASK, CoreNames.MASK_OPS,
        )
        for (field in component.fields) {
            body.beginControlFlow("if (%T.test(mask, %L))", CoreNames.MASK_OPS, field.constant)
            body.add(FieldIo.read(component, field))
            body.endControlFlow()
        }
        body.addStatement("return mask")
        return FunSpec.builder("read")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("src", CoreNames.BIT_READER)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slot", INT)
            .returns(CoreNames.FIELD_MASK)
            .addCode(body.build())
            .build()
    }

    /**
     * `apply` mutates the caller's component in place, writing through the access path, so a
     * lowered composite keeps its identity: `component.position.x = …` restores the vector
     * that rendering and physics already hold a reference to rather than replacing it.
     */
    private fun apply(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        for (field in component.fields) {
            body.beginControlFlow("if (%T.test(mask, %L))", CoreNames.MASK_OPS, field.constant)
            body.add(FieldIo.apply(field))
            body.endControlFlow()
        }
        return FunSpec.builder("apply")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("store", CoreNames.FIELD_STORE)
            .addParameter("slot", INT)
            .addParameter("component", component.className)
            .addParameter("mask", CoreNames.FIELD_MASK)
            .returns(UNIT)
            .addCode(body.build())
            .build()
    }

    private fun getField(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        if (component.fields.isEmpty()) {
            body.addStatement(
                "throw %T(TYPE_NAME, fieldIndex, FIELD_COUNT)",
                CoreNames.NO_SUCH_FIELD_INDEX,
            )
        } else {
            body.beginControlFlow("return when (fieldIndex)")
            for (field in component.fields) {
                body.add("%L -> ", field.constant).add(FieldIo.access(field)).add("\n")
            }
            body.addStatement(
                "else -> throw %T(TYPE_NAME, fieldIndex, FIELD_COUNT)",
                CoreNames.NO_SUCH_FIELD_INDEX,
            )
            body.endControlFlow()
        }
        return FunSpec.builder("getField")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("component", component.className)
            .addParameter("fieldIndex", INT)
            .returns(ANY.copy(nullable = true))
            .addCode(body.build())
            .build()
    }

    private fun setField(component: ReplicatedComponent): FunSpec {
        val body = CodeBlock.builder()
        if (component.fields.isEmpty()) {
            body.addStatement(
                "throw %T(TYPE_NAME, fieldIndex, FIELD_COUNT)",
                CoreNames.NO_SUCH_FIELD_INDEX,
            )
        } else {
            body.beginControlFlow("when (fieldIndex)")
            for (field in component.fields) {
                body.add("%L -> ", field.constant)
                    .add(FieldIo.access(field))
                    .add(
                        " = value as? %T ?: throw IllegalArgumentException(TYPE_NAME + %S + value)\n",
                        field.declaredType,
                        ".${field.name} expects ${display(field.declaredType)}, got ",
                    )
            }
            body.addStatement(
                "else -> throw %T(TYPE_NAME, fieldIndex, FIELD_COUNT)",
                CoreNames.NO_SUCH_FIELD_INDEX,
            )
            body.endControlFlow()
        }
        return FunSpec.builder("setField")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("component", component.className)
            .addParameter("fieldIndex", INT)
            .addParameter("value", ANY.copy(nullable = true))
            .returns(UNIT)
            .addCode(body.build())
            .build()
    }

    /** How a type is spelled in a runtime error message: the simple name, not the FQN. */
    private fun display(type: TypeName): String =
        if (type is ClassName) type.simpleNames.joinToString(".") else type.toString()
}
