package dev.wildware.udea.codegen

import dev.wildware.udea.codegen.protocol.NetComponentsManifest
import java.io.File
import java.security.MessageDigest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import org.junit.jupiter.api.io.TempDir

/**
 * Generated files are a pure function of the sources: two clean builds produce byte-identical
 * output.
 *
 * This is not tidiness. `net-protocol.lock` is diffed by CI, generated sources are reviewed as
 * diffs, and a build cache is only sound if the same inputs give the same bytes. A generator that
 * embeds a timestamp, an absolute path or an iteration order that depends on a `HashMap` breaks
 * all three at once — and does so intermittently, which is the expensive way to find out.
 *
 * The property is asserted several ways, over generated **sources** and generated **resources**
 * both: the bytes on disk match a checked-in hash, a second processor run over identical sources
 * reproduces those bytes exactly, declaration order in the source moves nothing, and the output
 * contains nothing machine-specific.
 *
 * Resources were outside all of it until issue #274. `expected-generated-hashes.txt` is keyed on
 * `GeneratedSources.relativePaths()`, which filters `extension == "kt"`, so `net-protocol.lock`,
 * the tool manifest and the component manifest were generated, shipped and never compared. That
 * stopped being theoretical when the component manifest arrived, because its correctness *is* an
 * ordering: two machines emitting the same names in different orders mint different component
 * type ids from identical sources, and `protoHash` reports agreement while two peers decode each
 * other's packets as the wrong component type.
 */
class GeneratedFileDeterminismTest {

    @Test
    fun `the generated files match their checked-in hashes`() {
        assertEquals(
            expectedHashes,
            actualHashes(),
            "generated output changed. If that was intended, re-run with " +
                "-P$UPDATE_PROPERTY=true and review the diff of the generated sources; if it was " +
                "not, the emitter has become non-deterministic.",
        )
    }

    @Test
    fun `the hash file covers every generated file`() {
        assertTrue(
            expectedHashes.isNotEmpty(),
            "no checked-in hashes; regenerate with -P$UPDATE_PROPERTY=true",
        )
        assertEquals(
            GeneratedSources.relativePaths().toSet(),
            expectedHashes.keys,
            "the hash file and the generated files disagree about which files exist",
        )
    }

    @Test
    fun `re-running the processor over the same sources reproduces the same bytes`(
        @TempDir first: File,
        @TempDir second: File,
    ) {
        val sources = mapOf("Source.kt" to SOURCE)

        val a = ProcessorHarness.run(first, sources)
        val b = ProcessorHarness.run(second, sources)

        assertEquals(emptyList(), a.errors)
        assertEquals(a.generatedFiles.map { it.name }, b.generatedFiles.map { it.name })
        for ((left, right) in a.generatedFiles.zip(b.generatedFiles)) {
            assertEquals(
                sha256(left.readBytes()),
                sha256(right.readBytes()),
                "${left.name} differed between two runs over identical sources",
            )
        }
    }

    @Test
    fun `declaration order in the source cannot change the generated bytes`(
        @TempDir first: File,
        @TempDir second: File,
    ) {
        // Bit indices come from the property *names*, so reordering the declarations must be a
        // no-op. If it is not, moving a property in a component silently changes the wire format.
        val ordered = ProcessorHarness.run(first, mapOf("Source.kt" to SOURCE))
        val shuffled = ProcessorHarness.run(second, mapOf("Source.kt" to SOURCE_REORDERED))

        assertEquals(emptyList(), shuffled.errors)
        assertEquals(
            ordered.generatedSource("CrateReplicator.kt"),
            shuffled.generatedSource("CrateReplicator.kt"),
        )
    }

    @Test
    fun `the machine-specific scan matches a real path and not the schema dialect URL`() {
        // A scanner that matches nothing passes vacuously forever, and this one was narrowed
        // to let a URL through — so both halves of that narrowing are pinned here.
        assertTrue(MACHINE_PATH.containsMatchIn("C:" + File.separator + "Users" + File.separator + "someone"))
        assertTrue(MACHINE_PATH.containsMatchIn("/Users/someone/project"))
        assertTrue(MACHINE_PATH.containsMatchIn("/home/someone/project"))
        assertFalse(
            MACHINE_PATH.containsMatchIn("https://json-schema.org/draft/2020-12/schema"),
            "the dialect URL a generated inputSchema declares is not a machine path",
        )
    }

    @Test
    fun `every generated resource is byte-identical across two runs`(
        @TempDir first: File,
        @TempDir second: File,
    ) {
        // The hole this closes: `expected-generated-hashes.txt` covers `.kt` files alone
        // (`GeneratedSources.files` filters `extension == "kt"`), so a generated **resource** was
        // outside every determinism check this build has. That mattered the moment issue #274
        // added a resource whose correctness *is* an ordering: two machines emitting the same
        // component names in different orders would mint different ids from the same source,
        // `protoHash` would report agreement, and two peers would decode each other's packets as
        // the wrong component type - the exact failure `udea.projectComponents` exists to stop.
        val sources = mapOf("Source.kt" to MODULE_SOURCE)

        val a = ProcessorHarness.run(first, sources, MODULE_OPTIONS)
        val b = ProcessorHarness.run(second, sources, MODULE_OPTIONS)

        assertEquals(emptyList(), a.errors)
        assertTrue(
            a.generatedResources.isNotEmpty(),
            "a comparison of two empty maps passes forever; this run must emit resources",
        )
        // Map equality compares the *contents*, so this is byte equality per resource as well as
        // agreement about which resources exist.
        assertEquals(a.generatedResources, b.generatedResources)
    }

    @Test
    fun `the component manifest is sorted, not in declaration order`(@TempDir workDir: File) {
        // `MODULE_SOURCE` declares Zebra before Aardvark. A resource in declaration order would
        // pass any assertion about *which* names are present - a set comparison cannot see an
        // order - so what is asserted is the order itself, against a source that disagrees with
        // it.
        val run = ProcessorHarness.run(workDir, mapOf("Source.kt" to MODULE_SOURCE), MODULE_OPTIONS)

        assertEquals(emptyList(), run.errors)
        assertEquals(
            "fixtures.Aardvark\nfixtures.Zebra\n",
            run.generatedResources.getValue("udea/Moba-net-components.txt"),
        )
    }

    @Test
    fun `the component manifest emitter sorts what it is handed`() {
        // The end-to-end case above cannot kill a mutation of this sort: `UdeaSymbolProcessor`
        // orders its components by qualified name before any writer sees them, so the manifest
        // would come out sorted with `render`'s own sort deleted. The pure function is where
        // that mutation is observable, so it is tested where it can fail.
        assertEquals(
            "a.Aardvark\nz.Zebra\n",
            NetComponentsManifest.render(listOf("z.Zebra", "a.Aardvark")),
        )
    }

    @Test
    fun `nothing machine-specific reaches a generated file or resource`() {
        val offenders = mutableListOf<String>()
        val userName = System.getProperty("user.name").orEmpty()
        for (file in GeneratedSources.files + GeneratedSources.resources) {
            file.readLines().forEachIndexed { index, line ->
                val reason = when {
                    MACHINE_PATH.containsMatchIn(line) -> "an absolute path"
                    TIMESTAMP.containsMatchIn(line) -> "a timestamp"
                    userName.isNotBlank() && userName in line -> "the building user's name"
                    else -> null
                }
                if (reason != null) offenders += "${file.name}:${index + 1}: $reason -> ${line.trim()}"
            }
        }
        assertEquals(emptyList(), offenders, "machine-specific content in generated code")
    }

    @Test
    fun `the manifest this module really emitted is sorted`() {
        // The artefact on disk, not a harness run: `kspTestKotlin` wrote it from this module's
        // own fixture components, which is the path every real module takes.
        val manifest = assertNotNull(
            GeneratedSources.resources.singleOrNull { it.name.endsWith("-net-components.txt") },
            "no component manifest under ${GeneratedSources.resourceDirectory.absolutePath}; " +
                "got ${GeneratedSources.resources.map { it.name }}",
        )
        val names = manifest.readLines().filter(String::isNotBlank)

        assertTrue(names.isNotEmpty(), "an empty manifest would pass any ordering assertion")
        assertEquals(names.sorted(), names, "the id space is sorted names, and this is that list")
    }

    private companion object {
        const val UPDATE_PROPERTY = "udea.updateGeneratedHashes"

        /** Two components declared in the order that is **not** their sorted order. */
        val MODULE_SOURCE = """
            package fixtures

            import dev.wildware.udea.annotations.Net
            import dev.wildware.udea.annotations.Replicated

            @Replicated
            class Zebra(@Net var stripes: Int = 0)

            @Replicated
            class Aardvark(@Net var snout: Float = 0f)
        """.trimIndent()

        /** What a module emitting a wire protocol is handed: its name, and the project id space. */
        val MODULE_OPTIONS = mapOf(
            CodegenOptions.MODULE_NAME to "Moba",
            CodegenOptions.REGISTRY_MODULES to "Moba",
            CodegenOptions.PROJECT_COMPONENTS to "fixtures.Aardvark,fixtures.Zebra",
        )

        /**
         * A Windows drive letter or a Unix home directory.
         *
         * The lookbehind is what keeps a URL out of it: a generated `inputSchema` names the
         * JSON Schema dialect it is written in, and `https://` ends in `s:/` — one letter, a
         * colon and a slash, which is a drive path if you do not look at the character before
         * it. Matching that would have made the only two choices "drop this check" or "stop
         * declaring the dialect", and both are worse than a lookbehind.
         */
        val MACHINE_PATH = Regex("""(?<![A-Za-z])[A-Za-z]:[\\/]|/home/|/Users/""")
        val TIMESTAMP = Regex("""\b(19|20)\d{2}-\d{2}-\d{2}\b|\b\d{2}:\d{2}:\d{2}\b""")

        /**
         * Read once per class, and rewritten first when the update flag is set — so no test here
         * depends on having run after another one.
         */
        val expectedHashes: Map<String, String> by lazy {
            if (System.getProperty(UPDATE_PROPERTY) == "true") write(actualHashes())
            read()
        }

        fun actualHashes(): Map<String, String> = GeneratedSources.files.associate { file ->
            file.relativeTo(GeneratedSources.directory).invariantSeparatorsPath to
                sha256(file.readBytes())
        }

        fun read(): Map<String, String> {
            val file = hashFile()
            if (!file.isFile) return emptyMap()
            return file.readLines()
                .map(String::trim)
                .filter { it.isNotEmpty() && !it.startsWith("#") }
                .associate { line ->
                    val separator = line.lastIndexOf("  ")
                    line.substring(0, separator) to line.substring(separator + 2)
                }
        }

        fun write(hashes: Map<String, String>) {
            val file = hashFile()
            file.parentFile.mkdirs()
            file.writeText(
                buildString {
                    append("# SHA-256 of every file udea-codegen generates for its fixture components.\n")
                    append("# Regenerate with: gradlew :udea-codegen:test -P$UPDATE_PROPERTY=true\n")
                    for ((path, hash) in hashes.toSortedMap()) {
                        append(path).append("  ").append(hash).append('\n')
                    }
                },
            )
        }

        fun hashFile(): File = ModuleRoot.file("src/test/resources/expected-generated-hashes.txt")

        fun sha256(bytes: ByteArray): String =
            MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

        val SOURCE = """
            package fixtures

            import dev.wildware.udea.annotations.Net
            import dev.wildware.udea.annotations.Replicated
            import dev.wildware.udea.annotations.Sim

            @Replicated
            class Crate(
                @Net var weight: Float = 0f,
                @Net var sealed: Boolean = false,
                @Sim var contents: Int = 0,
            )
        """.trimIndent()

        val SOURCE_REORDERED = """
            package fixtures

            import dev.wildware.udea.annotations.Net
            import dev.wildware.udea.annotations.Replicated
            import dev.wildware.udea.annotations.Sim

            @Replicated
            class Crate(
                @Sim var contents: Int = 0,
                @Net var sealed: Boolean = false,
                @Net var weight: Float = 0f,
            )
        """.trimIndent()
    }
}
