package dev.wildware.udea.codegen

import java.io.File
import java.security.MessageDigest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.io.TempDir

/**
 * Generated files are a pure function of the sources: two clean builds produce byte-identical
 * output.
 *
 * This is not tidiness. `net-protocol.lock` is diffed by CI, generated sources are reviewed as
 * diffs, and a build cache is only sound if the same inputs give the same bytes. A generator that
 * embeds a timestamp, an absolute path or an iteration order that depends on a `HashMap` breaks
 * all three at once — and does so intermittently, which is the expensive way to find out.
 *
 * The property is asserted three ways: the bytes on disk match a checked-in hash, a second
 * processor run over identical sources reproduces those bytes exactly, and the output contains
 * nothing machine-specific.
 */
class GeneratedFileDeterminismTest {

    @Test
    fun `the generated files match their checked-in hashes`() {
        assertEquals(
            expectedHashes,
            actualHashes(),
            "generated output changed. If that was intended, re-run with " +
                "-P$UPDATE_PROPERTY=true and review the diff of the generated sources; if it was " +
                "not, the emitter has become non-deterministic.",
        )
    }

    @Test
    fun `the hash file covers every generated file`() {
        assertTrue(
            expectedHashes.isNotEmpty(),
            "no checked-in hashes; regenerate with -P$UPDATE_PROPERTY=true",
        )
        assertEquals(
            GeneratedSources.relativePaths().toSet(),
            expectedHashes.keys,
            "the hash file and the generated files disagree about which files exist",
        )
    }

    @Test
    fun `re-running the processor over the same sources reproduces the same bytes`(
        @TempDir first: File,
        @TempDir second: File,
    ) {
        val sources = mapOf("Source.kt" to SOURCE)

        val a = ProcessorHarness.run(first, sources)
        val b = ProcessorHarness.run(second, sources)

        assertEquals(emptyList(), a.errors)
        assertEquals(a.generatedFiles.map { it.name }, b.generatedFiles.map { it.name })
        for ((left, right) in a.generatedFiles.zip(b.generatedFiles)) {
            assertEquals(
                sha256(left.readBytes()),
                sha256(right.readBytes()),
                "${left.name} differed between two runs over identical sources",
            )
        }
    }

    @Test
    fun `declaration order in the source cannot change the generated bytes`(
        @TempDir first: File,
        @TempDir second: File,
    ) {
        // Bit indices come from the property *names*, so reordering the declarations must be a
        // no-op. If it is not, moving a property in a component silently changes the wire format.
        val ordered = ProcessorHarness.run(first, mapOf("Source.kt" to SOURCE))
        val shuffled = ProcessorHarness.run(second, mapOf("Source.kt" to SOURCE_REORDERED))

        assertEquals(emptyList(), shuffled.errors)
        assertEquals(
            ordered.generatedSource("CrateReplicator.kt"),
            shuffled.generatedSource("CrateReplicator.kt"),
        )
    }

    @Test
    fun `nothing machine-specific reaches a generated file`() {
        val offenders = mutableListOf<String>()
        val userName = System.getProperty("user.name").orEmpty()
        for (file in GeneratedSources.files) {
            file.readLines().forEachIndexed { index, line ->
                val reason = when {
                    MACHINE_PATH.containsMatchIn(line) -> "an absolute path"
                    TIMESTAMP.containsMatchIn(line) -> "a timestamp"
                    userName.isNotBlank() && userName in line -> "the building user's name"
                    else -> null
                }
                if (reason != null) offenders += "${file.name}:${index + 1}: $reason -> ${line.trim()}"
            }
        }
        assertEquals(emptyList(), offenders, "machine-specific content in generated code")
    }

    private companion object {
        const val UPDATE_PROPERTY = "udea.updateGeneratedHashes"

        val MACHINE_PATH = Regex("""[A-Za-z]:[\\/]|/home/|/Users/""")
        val TIMESTAMP = Regex("""\b(19|20)\d{2}-\d{2}-\d{2}\b|\b\d{2}:\d{2}:\d{2}\b""")

        /**
         * Read once per class, and rewritten first when the update flag is set — so no test here
         * depends on having run after another one.
         */
        val expectedHashes: Map<String, String> by lazy {
            if (System.getProperty(UPDATE_PROPERTY) == "true") write(actualHashes())
            read()
        }

        fun actualHashes(): Map<String, String> = GeneratedSources.files.associate { file ->
            file.relativeTo(GeneratedSources.directory).invariantSeparatorsPath to
                sha256(file.readBytes())
        }

        fun read(): Map<String, String> {
            val file = hashFile()
            if (!file.isFile) return emptyMap()
            return file.readLines()
                .map(String::trim)
                .filter { it.isNotEmpty() && !it.startsWith("#") }
                .associate { line ->
                    val separator = line.lastIndexOf("  ")
                    line.substring(0, separator) to line.substring(separator + 2)
                }
        }

        fun write(hashes: Map<String, String>) {
            val file = hashFile()
            file.parentFile.mkdirs()
            file.writeText(
                buildString {
                    append("# SHA-256 of every file udea-codegen generates for its fixture components.\n")
                    append("# Regenerate with: gradlew :udea-codegen:test -P$UPDATE_PROPERTY=true\n")
                    for ((path, hash) in hashes.toSortedMap()) {
                        append(path).append("  ").append(hash).append('\n')
                    }
                },
            )
        }

        fun hashFile(): File = ModuleRoot.file("src/test/resources/expected-generated-hashes.txt")

        fun sha256(bytes: ByteArray): String =
            MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

        val SOURCE = """
            package fixtures

            import dev.wildware.udea.annotations.Net
            import dev.wildware.udea.annotations.Replicated
            import dev.wildware.udea.annotations.Sim

            @Replicated
            class Crate(
                @Net var weight: Float = 0f,
                @Net var sealed: Boolean = false,
                @Sim var contents: Int = 0,
            )
        """.trimIndent()

        val SOURCE_REORDERED = """
            package fixtures

            import dev.wildware.udea.annotations.Net
            import dev.wildware.udea.annotations.Replicated
            import dev.wildware.udea.annotations.Sim

            @Replicated
            class Crate(
                @Sim var contents: Int = 0,
                @Net var sealed: Boolean = false,
                @Net var weight: Float = 0f,
            )
        """.trimIndent()
    }
}
