package dev.wildware.udea.codegen.agent

import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STAR
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asTypeName
import kotlin.reflect.KClass

/**
 * Emits one `object <Owner>AgentState : AgentStateSource<Owner>` per class declaring
 * `@AgentState` properties.
 *
 * ## Allocation-free by construction
 *
 * `write` is a straight run of `out.put("key", source.property)` calls against a `GameStateSink`
 * whose overloads take the primitive directly. Nothing here boxes, builds a map, formats a
 * number or creates an intermediate object; the digest budget is 0.3ms at 500 entities (spec
 * 6, Phase 1 exit) and a digest that allocated once per published scalar would spend it on
 * garbage. An enum publishes `.name`, which is an interned constant rather than a new string.
 *
 * ## Nothing here is in the replication field space
 *
 * There is no mask, no store, no index and no `Replicator` in this file, and that is the
 * design and not an omission - see [AgentStateBuilder].
 */
internal object AgentStateEmitter {

    fun emit(model: AgentStateModel): FileSpec = FileSpec.builder(model.owner.packageName, model.objectName)
        .addFileComment("Generated by udea-codegen from @AgentState on %L.\nDo not edit.", model.owner.simpleName)
        .addType(
            TypeSpec.objectBuilder(model.objectName)
                // Matched to the declaring class rather than always public: see
                // [AgentStateModel.internal].
                .addModifiers(if (model.internal) KModifier.INTERNAL else KModifier.PUBLIC)
                .addSuperinterface(AgentNames.AGENT_STATE_SOURCE.parameterizedBy(model.owner))
                .addKdoc(
                    "The `game` block [%T] contributes to the agent's `/state` digest.\n\n" +
                        "Each value is read by direct property access and appended straight to " +
                        "the digest buffer, so publishing a scalar costs no allocation. These " +
                        "properties take no `FieldMask` bit and no `FieldStore` slot: " +
                        "`@AgentState` is an agent-only channel and is not replicated, not " +
                        "snapshotted and not restored by a rewind.\n",
                    model.owner,
                )
                .addProperty(
                    PropertySpec.builder("names", LIST.parameterizedBy(STRING), KModifier.OVERRIDE)
                        .addKdoc(
                            "The digest keys this source publishes, sorted. The runtime index " +
                                "reads them to reject two modules publishing one key, which no " +
                                "single KSP round can see.\n",
                        )
                        .initializer(namesInitializer(model))
                        .build(),
                )
                .addProperty(
                    PropertySpec.builder(
                        "owner",
                        KClass::class.asTypeName().parameterizedBy(STAR),
                        KModifier.OVERRIDE,
                    )
                        .addKdoc(
                            "The class these properties are declared on, as a class literal. " +
                                "`AgentStateIndex` pairs it with the instance the host " +
                                "registered: `T` is erased, so an index holding " +
                                "`AgentStateSource<*>` has no other way to know which object " +
                                "this `write` reads from.\n",
                        )
                        .initializer("%T::class", model.owner)
                        .build(),
                )
                .addFunction(
                    FunSpec.builder("write")
                        .addModifiers(KModifier.OVERRIDE)
                        .addParameter("source", model.owner)
                        .addParameter("out", AgentNames.GAME_STATE_SINK)
                        .addCode(writeBody(model))
                        .build(),
                )
                .build(),
        )
        .build()

    private fun namesInitializer(model: AgentStateModel): CodeBlock =
        CodeBlock.builder()
            .add("listOf(")
            .apply {
                model.entries.forEachIndexed { position, entry ->
                    if (position > 0) add(", ")
                    add("%S", entry.name)
                }
            }
            .add(")")
            .build()

    private fun writeBody(model: AgentStateModel): CodeBlock {
        val body = CodeBlock.builder()
        for (entry in model.entries) {
            when (entry.kind) {
                AgentStateKind.ENUM -> body.add(
                    "out.put(%S, source.%N.name)\n",
                    entry.name,
                    entry.propertyName,
                )
                else -> body.add("out.put(%S, source.%N)\n", entry.name, entry.propertyName)
            }
        }
        return body.build()
    }
}
