package dev.wildware.udea.codegen.agent

import com.squareup.kotlinpoet.ANY
import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STAR
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asTypeName
import dev.wildware.udea.codegen.CoreNames
import kotlin.reflect.KClass

/**
 * Emits one `object <Owner><Fn>Tool : AgentToolDef<Owner>` per `@AgentTool` function.
 *
 * ## Straight-line, and that is the whole point
 *
 * The generated `invoke` converts each argument and calls the function directly. No reflection,
 * so the agent surface survives R8 (spec 3.1); no map lookup, because conversion goes through
 * `AgentCommand`'s typed accessors; no `when` on a runtime type, so adding a supported argument
 * type is a change to this emitter and not a silent fallback at run time.
 *
 * ## Every failure is a `BadArgumentException` naming the argument
 *
 * A tool call is a query string a model wrote, so wrong input is the normal case rather than
 * the exceptional one. `AgentCommand.int`/`float`/`bool`/`str` already throw
 * `BadArgumentException(tool, argument, supplied, expected)`, and `AgentDispatcher` already
 * turns that into `ok:false` with kind `bad_argument`. Generated code therefore reuses them
 * instead of introducing a second failure type the dispatcher would have to learn — which is
 * how Phase 1's "a throwing tool lands as `ok:false` without stalling the loop" is met by
 * construction rather than by a second mechanism that agrees with the first today.
 */
internal object ToolEmitter {

    /** The local holding the raw query text where a conversion needs it twice. */
    private const val RAW = "raw"

    fun emit(tool: ToolModel): FileSpec = FileSpec.builder(tool.owner.packageName, tool.objectName)
        .addFileComment(
            "Generated by udea-codegen from @AgentTool %L.%L.\nDo not edit.",
            tool.owner.simpleName,
            tool.functionName,
        )
        .addType(
            TypeSpec.objectBuilder(tool.objectName)
                // Matched to the annotated function rather than always public: see
                // [ToolModel.internal].
                .addModifiers(if (tool.internal) KModifier.INTERNAL else KModifier.PUBLIC)
                // A tool that asked for the context of the command it is serving implements the
                // wider interface, which is what `ToolIndex` checks for before passing one in.
                // See `ToolModel.contextParameter` for the single reason a tool needs one.
                .addSuperinterface(
                    if (tool.contextParameter == null) {
                        AgentNames.AGENT_TOOL_DEF.parameterizedBy(tool.owner)
                    } else {
                        AgentNames.CONTEXTUAL_TOOL_DEF.parameterizedBy(tool.owner)
                    },
                )
                .addKdoc(
                    "The `%L` tool, generated from [%T.%L].\n\n" +
                        "Its schema and its argument coercion come from one model, so the " +
                        "manifest cannot advertise an argument the dispatcher does not " +
                        "accept. Every conversion failure is a [%T] naming the argument.\n",
                    tool.name,
                    tool.owner,
                    tool.functionName,
                    AgentNames.BAD_ARGUMENT,
                )
                .addProperty(
                    PropertySpec.builder("name", STRING, KModifier.OVERRIDE)
                        .initializer("%S", tool.name)
                        .build(),
                )
                .addProperty(
                    PropertySpec.builder("description", STRING, KModifier.OVERRIDE)
                        .initializer("%S", tool.description)
                        .build(),
                )
                .addProperty(
                    PropertySpec.builder(
                        "args",
                        LIST.parameterizedBy(AgentNames.AGENT_TOOL_ARG),
                        KModifier.OVERRIDE,
                    )
                        .initializer(argsInitializer(tool))
                        .build(),
                )
                .addProperty(
                    PropertySpec.builder("inputSchema", STRING, KModifier.OVERRIDE)
                        .addKdoc(
                            "The JSON Schema the bridge serves verbatim as " +
                                "`tools[].inputSchema`. A string constant rather than a " +
                                "structure built at start-up: it never varies, and the agent " +
                                "host serves it by concatenation.\n",
                        )
                        .initializer("%S", JsonText.renderCompact(ToolManifest.schemaOf(tool)))
                        .build(),
                )
                .addProperty(
                    PropertySpec.builder(
                        "owner",
                        KClass::class.asTypeName().parameterizedBy(STAR),
                        KModifier.OVERRIDE,
                    )
                        .addKdoc(
                            "The toolset this tool is a member of, as a class literal. " +
                                "`ToolIndex` pairs it with the instance the host registered: " +
                                "`T` is erased, so an index holding `AgentToolDef<*>` has no " +
                                "other way to know which receiver this `invoke` down-casts to. " +
                                "A class literal is a genuine reference, so R8 keeps the class " +
                                "and nothing is looked up; a name would be a string the " +
                                "shrinker cannot follow.\n",
                        )
                        .initializer("%T::class", tool.owner)
                        .build(),
                )
                .addFunctions(invocations(tool))
                .build(),
        )
        .build()

    /**
     * The one or two `invoke` overrides.
     *
     * A context-free tool has the one `AgentToolDef` declares. A tool that asked for a context
     * has both, and the two-argument one **throws**: it is unreachable through `ToolIndex`,
     * which calls the three-argument overload for a `ContextualToolDef`, and a tool in this
     * position needs a context to do its work at all. Running half of it and answering as
     * though it had run is the one outcome worse than refusing - `time.step` would confirm
     * without having stepped.
     */
    private fun invocations(tool: ToolModel): List<FunSpec> {
        val contextual = tool.contextParameter ?: return listOf(
            FunSpec.builder("invoke")
                .addModifiers(KModifier.OVERRIDE)
                .addParameter("receiver", tool.owner)
                .addParameter("command", AgentNames.AGENT_COMMAND)
                .returns(ANY.copy(nullable = true))
                .addCode(dispatch(tool, contextArgument = null))
                .build(),
        )
        return listOf(
            FunSpec.builder("invoke")
                .addKdoc(
                    "Unreachable through `ToolIndex`, which calls the three-argument overload " +
                        "for a `ContextualToolDef`. It throws rather than running [%T.%L] " +
                        "without the context it declared: answering as though the work had " +
                        "happened is worse than refusing.\n",
                    tool.owner,
                    tool.functionName,
                )
                .addModifiers(KModifier.OVERRIDE)
                .addParameter("receiver", tool.owner)
                .addParameter("command", AgentNames.AGENT_COMMAND)
                .returns(ANY.copy(nullable = true))
                .addStatement(
                    "throw %T(%S)",
                    UnsupportedOperationException::class,
                    "${tool.name} needs the AgentContext of the command it is serving; call " +
                        "the three-argument invoke, which is what ToolIndex does for a " +
                        "ContextualToolDef",
                )
                .build(),
            FunSpec.builder("invoke")
                .addModifiers(KModifier.OVERRIDE)
                .addParameter("receiver", tool.owner)
                .addParameter("command", AgentNames.AGENT_COMMAND)
                .addParameter("context", AgentNames.AGENT_CONTEXT)
                .returns(ANY.copy(nullable = true))
                .addCode(dispatch(tool, contextArgument = contextual))
                .build(),
        )
    }

    private fun argsInitializer(tool: ToolModel): CodeBlock {
        if (tool.args.isEmpty()) return CodeBlock.of("emptyList()")
        return CodeBlock.builder()
            .add("listOf(\n")
            .indent()
            .apply {
                for (arg in tool.args) {
                    add(
                        "%T(name·=·%S, type·=·%S, description·=·%S, required·=·%L, default·=·%L),\n",
                        AgentNames.AGENT_TOOL_ARG,
                        arg.name,
                        arg.jsonType,
                        arg.description,
                        arg.required,
                        arg.defaultText?.let { CodeBlock.of("%S", it) } ?: CodeBlock.of("null"),
                    )
                }
            }
            .unindent()
            .add(")")
            .build()
    }

    private fun dispatch(tool: ToolModel, contextArgument: String?): CodeBlock {
        val body = CodeBlock.builder()
        for (arg in tool.args) body.add(coerce(tool, arg))
        body.add("return receiver.%N(", tool.functionName)
        // Named arguments throughout, so the context is passed in whatever position the author
        // declared it without this emitter having to reproduce the parameter order.
        var written = 0
        if (contextArgument != null) {
            body.add("%N·=·context", contextArgument)
            written++
        }
        for (arg in tool.args) {
            if (written > 0) body.add(", ")
            body.add("%1N·=·%1N", arg.name)
            written++
        }
        body.add(")\n")
        return body.build()
    }

    /**
     * One argument, in one of three shapes, and the difference is exactly what the schema said:
     *
     * - required: `AgentCommand`'s accessor with no fallback, which throws when it is absent —
     *   which is what `required: [...]` promises a caller;
     * - optional with a default: the accessor's `fallback`, folded to the literal the
     *   `@Arg(default)` parsed to at build time, so the value an agent gets when it omits the
     *   argument is the value the manifest advertised;
     * - optional and nullable: absent is `null`, and the tool decides.
     */
    private fun coerce(tool: ToolModel, arg: ToolArgModel): CodeBlock {
        val declaredType = declaredType(arg)
        val builder = CodeBlock.builder().add("val %N: %T = ", arg.name, declaredType)
        if (arg.nullable) {
            // `contains` on AgentCommand, so "absent" and "present but empty" stay different.
            builder.add("if (%S·in·command) ", arg.name)
            builder.add(value(tool, arg, fallback = null))
            builder.add(" else null\n")
            return builder.build()
        }
        builder.add(value(tool, arg, fallback = arg.defaultText))
        builder.add("\n")
        return builder.build()
    }

    /** The converted value, throwing a `BadArgumentException` if the text will not convert. */
    private fun value(tool: ToolModel, arg: ToolArgModel, fallback: String?): CodeBlock {
        if (arg.list) {
            // A list travels as one query parameter, comma separated, because that is all a
            // query string offers - which is why the published schema types it `string` and
            // says so in the description rather than typing it `array`, a shape the bridge
            // would deliver here as the JSON text `["a","b"]` for this split to mangle.
            // Blank elements are kept rather than dropped: dropping them would make `a,,b`
            // silently mean `a,b`, and a silent reinterpretation of a model's input is the
            // failure this whole file is arranged to avoid.
            return CodeBlock.builder()
                .add("command.str(%S%L).split(',').map·{ %N ->\n", arg.name, textFallback(fallback), RAW)
                .indent()
                .add(element(tool, arg, RAW))
                .add("\n")
                .unindent()
                .add("}")
                .build()
        }
        arg.kind.accessor?.let { accessor ->
            // The engine's own accessor: it converts, and it throws BadArgumentException with
            // this tool's name when it cannot. The fallback is the folded literal, so a default
            // that would not parse was a build error rather than a first-call surprise.
            val literal = fallback?.let {
                requireNotNull(ArgDefaults.literal(arg.kind, arg.enumType, arg.enumConstants, it)) {
                    "the builder rejects a default that will not fold"
                }
            }
            return CodeBlock.of("command.%N(%S%L)", accessor, arg.name, typedFallback(literal))
        }
        // Double, an enum and NetId have no accessor, so the raw text is read - with the
        // declared default as *text*, which is the form `AgentCommand.str` takes - and the
        // conversion below turns it into the parameter's type.
        return CodeBlock.builder()
            .add("command.str(%S%L).let·{ %N ->\n", arg.name, textFallback(fallback), RAW)
            .indent()
            .add(element(tool, arg, RAW))
            .add("\n")
            .unindent()
            .add("}")
            .build()
    }

    /** `, "1"` for a default read back as text, or nothing. */
    private fun textFallback(text: String?): CodeBlock =
        if (text == null) CodeBlock.of("") else CodeBlock.of(", %S", text)

    /** `, 4f` for a default folded into the parameter's own type, or nothing. */
    private fun typedFallback(literal: CodeBlock?): CodeBlock =
        if (literal == null) CodeBlock.of("") else CodeBlock.builder().add(", ").add(literal).build()

    /**
     * One value converted from the local named [source].
     *
     * Only the kinds `AgentCommand` has no accessor for reach here: `Double`, an enum and
     * `NetId`, plus every element of a list. Each ends in the same `BadArgumentException` the
     * accessors throw, so a caller sees one failure shape whichever argument was wrong.
     */
    private fun element(tool: ToolModel, arg: ToolArgModel, source: String): CodeBlock {
        val failure = CodeBlock.of(
            "throw %T(%S, %S, %N, %S)",
            AgentNames.BAD_ARGUMENT,
            tool.name,
            arg.name,
            source,
            expectation(arg),
        )
        val parsed = when (arg.kind) {
            ArgKind.INT -> CodeBlock.of("%N.toIntOrNull()", source)
            ArgKind.LONG -> CodeBlock.of("%N.toLongOrNull()", source)
            ArgKind.FLOAT -> CodeBlock.of("%N.toFloatOrNull()", source)
            ArgKind.DOUBLE -> CodeBlock.of("%N.toDoubleOrNull()", source)
            // The same mapping `AgentCommand.bool` applies, and not `toBooleanStrictOrNull`:
            // a scalar Boolean argument accepts 1 and 0, `ArgKind.BOOLEAN.expectation` tells
            // the agent so, and `ArgDefaults.literal` folds them for a default. An element of
            // a `List<Boolean>` that refused them would throw an error naming the two values
            // it had just rejected. An `if` chain and not a `when`: `GeneratedSourceShapeTest`
            // bans `when` in generated code outside the field index, the old generator's
            // `when (value) { is Float -> … }` is what that ban is aimed at, and widening it
            // for a two-branch value mapping would be paying for this in the wrong currency.
            ArgKind.BOOLEAN -> return CodeBlock.builder()
                .add("if (%1N == %2S || %1N == %3S) {\n", source, "true", "1")
                .indent().add("true\n").unindent()
                .add("} else if (%1N == %2S || %1N == %3S) {\n", source, "false", "0")
                .indent().add("false\n").unindent()
                .add("} else {\n")
                .indent().add(failure).add("\n").unindent()
                .add("}")
                .build()
            ArgKind.STRING -> return CodeBlock.of("%N", source)
            // `entries` is a compiler-synthesised array, not reflection, and the constant
            // *name* is the wire form rather than the ordinal: an agent reading "Sprinting"
            // in the schema must be able to send "Sprinting" back, and reordering the enum
            // must not silently change what a stored tool call means.
            ArgKind.ENUM -> CodeBlock.of(
                "%T.entries.firstOrNull·{ it.name == %N }",
                requireNotNull(arg.enumType) { "an ENUM argument must carry its enum type" },
                source,
            )
            ArgKind.NET_ID -> CodeBlock.of("%N.toIntOrNull()", source)
        }
        if (arg.kind != ArgKind.NET_ID) {
            return CodeBlock.builder().add(parsed).add("\n?: ").add(failure).build()
        }
        // NetId.ofRaw range-checks the reserved byte and throws IllegalArgumentException.
        // Converting it here is a boundary adaptation and not a swallow: the tool and argument
        // names are added and the original message is carried into `expected`, which is what
        // the agent is shown.
        return CodeBlock.builder()
            .add("val·word·=·")
            .add(parsed)
            .add("\n?: ")
            .add(failure)
            .add("\ntry·{ %T.ofRaw(word) } catch (e: IllegalArgumentException) {\n", CoreNames.NET_ID)
            .indent()
            .add(
                "throw %T(%S, %S, %N, %S·+·e.message)\n",
                AgentNames.BAD_ARGUMENT,
                tool.name,
                arg.name,
                source,
                "a valid NetId packed word: ",
            )
            .unindent()
            .add("}")
            .build()
    }

    private fun expectation(arg: ToolArgModel): String = when {
        arg.enumConstants.isNotEmpty() -> "one of ${arg.enumConstants.joinToString(", ")}"
        else -> arg.kind.expectation
    }

    private fun declaredType(arg: ToolArgModel): TypeName {
        val element = elementType(arg)
        val whole = if (arg.list) LIST.parameterizedBy(element) else element
        return whole.copy(nullable = arg.nullable)
    }

    private fun elementType(arg: ToolArgModel): TypeName = when (arg.kind) {
        ArgKind.INT -> Int::class.asTypeName()
        ArgKind.LONG -> Long::class.asTypeName()
        ArgKind.FLOAT -> Float::class.asTypeName()
        ArgKind.DOUBLE -> Double::class.asTypeName()
        ArgKind.BOOLEAN -> BOOLEAN
        ArgKind.STRING -> STRING
        ArgKind.ENUM -> requireNotNull(arg.enumType) { "an ENUM argument must carry its enum type" }
        ArgKind.NET_ID -> CoreNames.NET_ID
    }
}
