package dev.wildware.udea.assets.pack

import kotlin.io.encoding.Base64

/**
 * A real `.udeapak`, as bytes every target can read without a file system (issue #205).
 *
 * Written by `udea-assets-compiler`'s `BundleWriter` at `origin/kmp` 07eddef, before
 * `udea-assets` was ported: the `packassets` test corpus (typed kinds, references, floats and an
 * opaque `particle` kind), two stand-in atlas pages (page 0 eager, page 1 streamed) with regions
 * for both orc sheets, a streamed 300-byte audio section and an eager UTF-8 text blob.
 *
 * Base64 in source rather than a resource file because a Kotlin/Wasm or iOS test has no portable
 * way to open a test resource, and the point of this fixture is that every target reads the same
 * bytes. [GoldenPakExpected] is what the pre-port reader made of them.
 */
internal object GoldenPak {

    val bytes: ByteArray get() = Base64.decode(ENCODED)

    private val ENCODED: String = listOf(
        "VURFQQEAAAAAAAAAfUZHQs55FrDDxkDSkQWsbIAOKH0jKx3VMx2fOG70DOkGAAAAAQALAGF0bGFzLWluZGV46gAAAAAAAACi",
        "AgAAAgASAGF0bGFzL3BhZ2UwMDAwLnBuZ4wDAAAAAAAAYAAAAAAABQBncmFwaOwDAAAAAAAAUAYAAAQAEQB0ZXh0L2dyZWV0",
        "aW5nLnR4dDwKAAAAAAAAGQAAAAIBEgBhdGxhcy9wYWdlMDAwMS5wbmdVCgAAAAAAAEAAAAADARUAc291bmRzL29yYy9hdHRh",
        "Y2sub2dnlQoAAAAAAAAsAQAAEAAAABIAAABjaGFyYWN0ZXIvb3JjX2lkbGUXAAAAY2hhcmFjdGVyL29yY19pZGxlIzAwMDAX",
        "AAAAY2hhcmFjdGVyL29yY19pZGxlIzAwMDEXAAAAY2hhcmFjdGVyL29yY19pZGxlIzAwMDIXAAAAY2hhcmFjdGVyL29yY19p",
        "ZGxlIzAwMDMXAAAAY2hhcmFjdGVyL29yY19pZGxlIzAwMDQXAAAAY2hhcmFjdGVyL29yY19pZGxlIzAwMDUSAAAAY2hhcmFj",
        "dGVyL29yY193YWxrFwAAAGNoYXJhY3Rlci9vcmNfd2FsayMwMDAwFwAAAGNoYXJhY3Rlci9vcmNfd2FsayMwMDAxFwAAAGNo",
        "YXJhY3Rlci9vcmNfd2FsayMwMDAyFwAAAGNoYXJhY3Rlci9vcmNfd2FsayMwMDAzFwAAAGNoYXJhY3Rlci9vcmNfd2FsayMw",
        "MDA0FwAAAGNoYXJhY3Rlci9vcmNfd2FsayMwMDA1FwAAAGNoYXJhY3Rlci9vcmNfd2FsayMwMDA2FwAAAGNoYXJhY3Rlci9v",
        "cmNfd2FsayMwMDA3AgAAAIAAAABAAAAAgAAAAIAAAAAOAAAAAQAAAAAAAAAAABAAEAACAAAAAAAQAAAAEAAQAAMAAAAAACAA",
        "AAAQABAABAAAAAAAMAAAABAAEAAFAAAAAABAAAAAEAAQAAYAAAAAAFAAAAAQABAACAAAAAEAAAAgABAAEAAJAAAAAQAQACAA",
        "EAAQAAoAAAABACAAIAAQABAACwAAAAEAMAAgABAAEAAMAAAAAQBAACAAEAAQAA0AAAABAFAAIAAQABAADgAAAAEAYAAgABAA",
        "EAAPAAAAAQBwACAAEAAQAAIAAAAAAAAAAAAAAAYAAAAHAAAABgAAAAgAAAADChEYHyYtNDtCSVBXXmVsc3qBiI+WnaSrsrnA",
        "x87V3OPq8fj/Bg0UGyIpMDc+RUxTWmFob3Z9hIuSmaCnrrW8w8rR2N/m7fT7AgkQFx4lLDM6QUhPVl1ka3J5gIeOlZw5AAAA",
        "CQAAAGFiaWxpdGllcwIAAABhaQoAAABhbmltYXRpb25zBgAAAGF0dGFjawoAAABhdHRyaWJ1dGVzCQAAAGJsdWVwcmludBAA",
        "AABibHVlcHJpbnQvbWluaW9uEgAAAGJsdWVwcmludC9taW5pb24jMBIAAABibHVlcHJpbnQvbWluaW9uIzESAAAAYmx1ZXBy",
        "aW50L21pbmlvbiMyEAAAAGJsdWVwcmludC9wbGF5ZXISAAAAYmx1ZXByaW50L3BsYXllciMzDQAAAGNoYXJhY3Rlci9vcmMY",
        "AAAAY2hhcmFjdGVyL29yY19hdHRhY2tfY3VlEgAAAGNoYXJhY3Rlci9vcmNfZHVzdBIAAABjaGFyYWN0ZXIvb3JjX2lkbGUX",
        "AAAAY2hhcmFjdGVyL29yY19pZGxlX2FuaW0SAAAAY2hhcmFjdGVyL29yY193YWxrFwAAAGNoYXJhY3Rlci9vcmNfd2Fsa19h",
        "bmltBwAAAGNvbHVtbnMKAAAAY29tcG9uZW50cwYAAABjb25maWcQAAAAZGVmYXVsdENoYXJhY3RlciIAAABkZXYud2lsZHdh",
        "cmUudWRlYS5hc3NldHMuQmx1ZXByaW50IgAAAGRldi53aWxkd2FyZS51ZGVhLmFzc2V0cy5DaGFyYWN0ZXIjAAAAZGV2Lndp",
        "bGR3YXJlLnVkZWEuYXNzZXRzLkdhbWVDb25maWceAAAAZGV2LndpbGR3YXJlLnVkZWEuYXNzZXRzLkxldmVsIQAAAGRldi53",
        "aWxkd2FyZS51ZGVhLmFzc2V0cy5Tb3VuZEN1ZSgAAABkZXYud2lsZHdhcmUudWRlYS5hc3NldHMuU3ByaXRlQW5pbWF0aW9u",
        "JAAAAGRldi53aWxkd2FyZS51ZGVhLmFzc2V0cy5TcHJpdGVTaGVldAgAAABlbnRpdGllcwgAAABnYW1lVW5pdAYAAABoZWFs",
        "dGgEAAAAaWRsZQ0AAABpbmhlcml0ZWRGcm9tDQAAAGludGVycnVwdGlibGULAAAAbGV2ZWwvYXJlbmEIAAAAbGlmZXRpbWUE",
        "AAAAbG9vcAQAAABuYW1lCwAAAG5ldHdvcmthYmxlCAAAAHBhcnRpY2xlDQAAAHBpdGNoVmFyaWFuY2UEAAAAcm93cwUAAABz",
        "Y2FsZQUAAABzaGVldAQAAABzaXplBgAAAHNvdW5kcxUAAABzb3VuZHMvb3JjL2F0dGFjay5vZ2cUAAAAc3ByaXRlcy9vcmMv",
        "aWRsZS5wbmcUAAAAc3ByaXRlcy9vcmMvd2Fsay5wbmcHAAAAc3lzdGVtcwQAAAB0YWdzBAAAAHRlYW0HAAAAdGV4dHVyZQQA",
        "AAB0eXBlBgAAAHZvbHVtZQsAAAAGAAAAFwAAAAIAAAAUAAAACQEAAAAKAQAAADcAAAAFAQAAACIAAAAJAQAAAAUKAAAACgAA",
        "ABcAAAABAAAAFAAAAAkDAAAACgEAAAA3AAAABSgAAAAKAQAAADcAAAAFNQAAAAoBAAAANwAAAAUfAAAADAAAABgAAAAIAAAA",
        "AAAAAAkAAAAAAgAAAAoBAAAAIQAAAAcGAAAABAAAAAoAAAAAFAAAAAkAAAAAIAAAAAQAAPpDLgAAAASamZk+LwAAAAoBAAAA",
        "AwAAAAcDAAAANAAAAAkAAAAADQAAABsAAAADAAAAKgAAAATNzEw/LwAAAAkBAAAABjAAAAA4AAAABAAAAD8OAAAAKQAAAAEA",
        "AAAlAAAABAAAwD8PAAAAHQAAAAQAAAATAAAAAgYAAAArAAAAAgEAAAAsAAAABArXozw2AAAABjEAAAAQAAAAHAAAAAMAAAAj",
        "AAAAAQEmAAAAAQEtAAAABwUAAAARAAAAHQAAAAQAAAATAAAAAggAAAArAAAAAgEAAAAsAAAABArXozw2AAAABjIAAAASAAAA",
        "HAAAAAMAAAAjAAAAAQAmAAAAAQAtAAAABwcAAAAVAAAAGQAAAAEAAAAWAAAABwEAAAAkAAAAGgAAAAIAAAAeAAAACQQAAAAK",
        "AgAAAAUAAAAHAAAAACcAAAAFBwAAAAoCAAAABQAAAAcAAAAAJwAAAAUIAAAACgIAAAAFAAAABwAAAAAnAAAABQkAAAAKAgAA",
        "AAUAAAAHAQAAACcAAAAFCwAAADMAAAAJAAAAAGjDqWxsbywgw7xuw69jb2RlIHNlY3Rpb27/+vXw6+bh3NfSzcjDvrm0r6ql",
        "oJuWkYyHgn14c25pZF9aVVBLRkE8NzItKCMeGRQPCgUA+/bx7Ofi3djTzsnEWkVkBybB4IOiTWwPLsnoi6pVdBc20fCTsl18",
        "Hz7Z+Ju6pURnBiHA44KtTG8OKcjrirVUdxYx0POSvVx/HjnY+5qFpEdmASDD4o2sT24JKMvqlbRXdhEw0/KdvF9+GTjb+uWE",
        "p0ZhACPC7YyvTmkIK8r1lLdWcRAz0v2cv155GDvaxeSHpkFgAyLN7I+uSWgLKtX0l7ZRcBMy3fyfvll4GzolxOeGoUBjAi3M",
        "746pSGsKNdT3lrFQcxI93P+euVh7GgUkx+aBoENiDSzP7omoS2oVNNf2kbBTch083/6ZuFt6ZQQnxuGAo0JtDC/O6YirSnUU",
        "N9bxkLNSfRw/3vmYu1pFZAcmweCDok1sDy7J6IuqVXQXNtHwk7JdfB8+2fibuqVEZwYhwOOCrUxv",
    ).joinToString("")
}
