package dev.wildware.udea.assets.pack

/**
 * What the `.udeapak` reader made of [GoldenPak] **before** `udea-assets` was ported (issue #205),
 * as [describeBundle] prints it.
 *
 * Captured once from the JVM-only reader at `origin/kmp` 07eddef, in the commit before the port,
 * and never regenerated by a flag: a golden rewritten from the ported reader would compare that
 * reader with itself. If the format genuinely changes, this changes by hand in the same review as
 * the format, alongside [GoldenPak].
 */
internal const val GOLDEN_PAK_EXPECTED: String = """contentHash 7d464742ce7916b0c3c640d29105ac6c800e287d232b1dd5331d9f386ef40ce9
contentHashOf 7d464742ce7916b0c3c640d29105ac6c800e287d232b1dd5331d9f386ef40ce9
verifyContentHash true
eagerBytes 2411 streamedBytes 364
section atlas-index ATLAS_INDEX EAGER offset=234 length=674 read=674 fnv=158d1e12f54c3289
section atlas/page0000.png ATLAS_PAGE EAGER offset=908 length=96 read=96 fnv=2174b4c8b4e487a5
section graph GRAPH EAGER offset=1004 length=1616 read=1616 fnv=d23caa9a237a2064
section text/greeting.txt BLOB EAGER offset=2620 length=25 read=25 fnv=18aab957bf2ff087
section atlas/page0001.png ATLAS_PAGE STREAMED offset=2645 length=64 read=64 fnv=5d329f481ece9da5
section sounds/orc/attack.ogg AUDIO STREAMED offset=2709 length=300 read=300 fnv=faba2cf729e664c1
assets 11
asset 0 blueprint/minion Blueprint Blueprint(id=blueprint/minion, components=[ComponentSpec(type=ai, fields={})], tags=[], inheritedFrom=[blueprint/player])
asset 1 blueprint/player Blueprint Blueprint(id=blueprint/player, components=[ComponentSpec(type=networkable, fields={}), ComponentSpec(type=team, fields={}), ComponentSpec(type=gameUnit, fields={})], tags=[], inheritedFrom=[])
asset 2 character/orc Character Character(id=character/orc, size=0.3, health=500.0, animationSet=null, animations={idle=Ref<SpriteAnimation>(character/orc_idle_anim)}, sounds={attack=Ref<SoundCue>(character/orc_attack_cue)}, attributes={}, components=[], tags=[], abilities=[])
asset 3 character/orc_attack_cue SoundCue SoundCue(id=character/orc_attack_cue, sounds=[sounds/orc/attack.ogg], pitchVariance=0.8, volume=0.5)
asset 4 character/orc_dust OpaqueAsset OpaqueAsset(id=character/orc_dust, kind=particle, fields={lifetime=FloatValue(value=1.5)})
asset 5 character/orc_idle SpriteSheet SpriteSheet(id=character/orc_idle, texture=sprites/orc/idle.png, columns=6, rows=1, scale=0.02)
asset 6 character/orc_idle_anim SpriteAnimation SpriteAnimation(id=character/orc_idle_anim, sheet=Ref<SpriteSheet>(character/orc_idle), frameTime=0.1, loop=true, interruptible=true, notifies=[])
asset 7 character/orc_walk SpriteSheet SpriteSheet(id=character/orc_walk, texture=sprites/orc/walk.png, columns=8, rows=1, scale=0.02)
asset 8 character/orc_walk_anim SpriteAnimation SpriteAnimation(id=character/orc_walk_anim, sheet=Ref<SpriteSheet>(character/orc_walk), frameTime=0.1, loop=false, interruptible=false, notifies=[])
asset 9 config GameConfig GameConfig(id=config, defaultLevel=null, defaultCharacter=Ref<SpawnRecipe>(blueprint/player), backgroundTexture=null, network=NetworkConfig(tcpPort=28855, udpPort=28856), physics=PhysicsConfig(gravity=Vec2(x=0.0, y=-9.81)), lighting=null, ui=null, movementType=TopDown)
asset 10 level/arena Level Level(id=level/arena, systems=[], entities=[EntityDefinition(name=blueprint/minion#0, blueprint=Ref<SpawnRecipe>(blueprint/minion), components=[], tags=[], position=null), EntityDefinition(name=blueprint/minion#1, blueprint=Ref<SpawnRecipe>(blueprint/minion), components=[], tags=[], position=null), EntityDefinition(name=blueprint/minion#2, blueprint=Ref<SpawnRecipe>(blueprint/minion), components=[], tags=[], position=null), EntityDefinition(name=blueprint/player#3, blueprint=Ref<SpawnRecipe>(blueprint/player), components=[], tags=[], position=null)])
atlas pages [AtlasPageInfo(width=128, height=64), AtlasPageInfo(width=128, height=128)]
region AtlasRegion(name=character/orc_idle#0000, page=0, x=0, y=0, width=16, height=16)
region AtlasRegion(name=character/orc_idle#0001, page=0, x=16, y=0, width=16, height=16)
region AtlasRegion(name=character/orc_idle#0002, page=0, x=32, y=0, width=16, height=16)
region AtlasRegion(name=character/orc_idle#0003, page=0, x=48, y=0, width=16, height=16)
region AtlasRegion(name=character/orc_idle#0004, page=0, x=64, y=0, width=16, height=16)
region AtlasRegion(name=character/orc_idle#0005, page=0, x=80, y=0, width=16, height=16)
region AtlasRegion(name=character/orc_walk#0000, page=1, x=0, y=32, width=16, height=16)
region AtlasRegion(name=character/orc_walk#0001, page=1, x=16, y=32, width=16, height=16)
region AtlasRegion(name=character/orc_walk#0002, page=1, x=32, y=32, width=16, height=16)
region AtlasRegion(name=character/orc_walk#0003, page=1, x=48, y=32, width=16, height=16)
region AtlasRegion(name=character/orc_walk#0004, page=1, x=64, y=32, width=16, height=16)
region AtlasRegion(name=character/orc_walk#0005, page=1, x=80, y=32, width=16, height=16)
region AtlasRegion(name=character/orc_walk#0006, page=1, x=96, y=32, width=16, height=16)
region AtlasRegion(name=character/orc_walk#0007, page=1, x=112, y=32, width=16, height=16)
sheet character/orc_idle frames character/orc_idle#0000,character/orc_idle#0001,character/orc_idle#0002,character/orc_idle#0003,character/orc_idle#0004,character/orc_idle#0005
sheet character/orc_walk frames character/orc_walk#0000,character/orc_walk#0001,character/orc_walk#0002,character/orc_walk#0003,character/orc_walk#0004,character/orc_walk#0005,character/orc_walk#0006,character/orc_walk#0007
"""
