package dev.wildware.udea.codegen.gizmo

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STAR
import com.squareup.kotlinpoet.TypeSpec
import dev.wildware.udea.codegen.registry.RegistryEmitter

/**
 * Emits one `Gizmo` object per handle annotation, and a game's `<Game>GizmoRegistry` (issue #233).
 *
 * A generated gizmo is written exactly as a person would write it against the public API - the same
 * `handle(...)` call, the same `write(Component::field, ...)` - which is the point: an annotation is
 * shorthand, and `GeneratedGizmoTest` holds each kind to a hand-written twin. Every field is read by
 * direct property access and named by a property reference, so nothing is looked up by name at run
 * time, and the whole file is KotlinPoet.
 *
 * Every drag response computes a change from what [build] read when it declared the handle, because
 * the editor keeps the pressed handle for the whole drag while the drag itself changes the component.
 */
internal object GizmoEmitter {

    /** The file holding [model]'s gizmo. */
    fun emit(model: HandleModel): FileSpec {
        val component = model.component
        val gizmo = TypeSpec.objectBuilder(model.gizmo)
            .addModifiers(KModifier.INTERNAL)
            .addSuperinterface(EditorNames.GIZMO_INTERFACE.parameterizedBy(component))
            .addKdoc(
                "The gizmo `@%L` declares on [%T]. Generated by udea-codegen: edit the annotation, not this.\n",
                model.annotation,
                component,
            )
            .addProperty(
                PropertySpec.builder("component", EditorNames.COMPONENT_TYPE.parameterizedBy(component), KModifier.OVERRIDE)
                    .initializer("%T", component)
                    .build(),
            )
            .addFunction(
                FunSpec.builder("build")
                    .addModifiers(KModifier.OVERRIDE)
                    .receiver(EditorNames.GIZMO_SCOPE.parameterizedBy(component))
                    .addParameter("target", EditorNames.GIZMO_TARGET.parameterizedBy(component))
                    .addCode(body(model))
                    .build(),
            )
            .build()
        return FileSpec.builder(model.gizmo.packageName, model.gizmo.simpleName)
            .addFileComment("Generated by udea-codegen from @%L on %L.\nDo not edit.", model.annotation, component.canonicalName)
            .addType(gizmo)
            .build()
    }

    /**
     * `internal object <Game>GizmoRegistry : GizmoRegistry`, listing [gizmos] - each already an
     * expression, an object as itself or a class constructed - in the order given.
     */
    fun registry(name: ClassName, game: String, gizmos: List<CodeBlock>): FileSpec =
        FileSpec.builder(name.packageName, name.simpleName)
            .addFileComment("Generated by udea-codegen for %L's editor.\nDo not edit.", game)
            .addType(
                TypeSpec.objectBuilder(name)
                    .addModifiers(KModifier.INTERNAL)
                    .addSuperinterface(EditorNames.GIZMO_REGISTRY)
                    .addKdoc(
                        "Every gizmo %L's editor offers: one per handle annotation on its components, " +
                            "and every hand-written Gizmo in its editor source set.\n",
                        game,
                    )
                    .addProperty(
                        PropertySpec.builder(
                            "gizmos",
                            LIST.parameterizedBy(EditorNames.GIZMO_INTERFACE.parameterizedBy(STAR)),
                            KModifier.OVERRIDE,
                        )
                            .addKdoc("Every gizmo, in ascending fully-qualified class-name order.")
                            .initializer(RegistryEmitter.listInitializer(gizmos))
                            .build(),
                    )
                    .build(),
            )
            .build()

    private fun body(model: HandleModel): CodeBlock = when (model) {
        is HandleModel.Position -> position(model)
        is HandleModel.Size -> size(model)
        is HandleModel.Rotation -> rotation(model)
        is HandleModel.Reach -> reach(model)
    }

    /** At the fields' point; moved by the drag. On the ground plane in 2D, in the view's plane in 3D. */
    private fun position(model: HandleModel.Position): CodeBlock {
        val c = model.component
        val z = model.z
        return CodeBlock.builder()
            .addStatement("val x0 = target.component.%N", model.x)
            .addStatement("val y0 = target.component.%N", model.y)
            .apply { if (z != null) addStatement("val z0 = target.component.%N", z) }
            .beginControlFlow(
                "handle(%T(x0, y0, %L), %L, %L) { drag ->",
                EditorNames.WORLD_POINT,
                if (z != null) "z0" else "0f",
                if (z != null) sphere() else CodeBlock.of("%T.PlaneSquare(%T.XY)", EditorNames.HANDLE_SHAPE, EditorNames.PLANE),
                constraint(threeD = z != null),
            )
            .addStatement("write(%T::%N, x0 + drag.dx)", c, model.x)
            .addStatement("write(%T::%N, y0 + drag.dy)", c, model.y)
            .apply { if (z != null) addStatement("write(%T::%N, z0 + drag.dz)", c, z) }
            .endControlFlow()
            .build()
    }

    /** The box corner of a size centred on the entity; the size follows the corner, never below zero. */
    private fun size(model: HandleModel.Size): CodeBlock {
        val c = model.component
        val depth = model.depth
        return CodeBlock.builder()
            .addStatement("val origin = target.origin")
            .addStatement("val width0 = target.component.%N", model.width)
            .addStatement("val height0 = target.component.%N", model.height)
            .apply { if (depth != null) addStatement("val depth0 = target.component.%N", depth) }
            .beginControlFlow(
                "handle(%T(origin.x + width0 / 2f, origin.y + height0 / 2f, %L), %T.BoxCorner, %L) { drag ->",
                EditorNames.WORLD_POINT,
                if (depth != null) "origin.z + depth0 / 2f" else "origin.z",
                EditorNames.HANDLE_SHAPE,
                constraint(threeD = depth != null),
            )
            .addStatement("write(%T::%N, maxOf(0f, width0 + drag.spread(%T.X, origin)))", c, model.width, EditorNames.AXIS)
            .addStatement("write(%T::%N, maxOf(0f, height0 + drag.spread(%T.Y, origin)))", c, model.height, EditorNames.AXIS)
            .apply {
                if (depth != null) {
                    addStatement("write(%T::%N, maxOf(0f, depth0 + drag.spread(%T.Z, origin)))", c, depth, EditorNames.AXIS)
                }
            }
            .endControlFlow()
            .build()
    }

    /** A ring about the up axis at the entity; the field turns by the angle the drag turned. */
    private fun rotation(model: HandleModel.Rotation): CodeBlock =
        CodeBlock.builder()
            .addStatement("val origin = target.origin")
            .addStatement("val rotation0 = target.component.%N", model.field)
            .beginControlFlow(
                "handle(origin, %T.Ring(%T.Z), %L) { drag ->",
                EditorNames.HANDLE_SHAPE,
                EditorNames.AXIS,
                constraint(threeD = false),
            )
            .addStatement("write(%T::%N, rotation0 + drag.turnAbout(origin))", model.component, model.field)
            .endControlFlow()
            .build()

    /** On the rim along +X; the field follows the distance from the entity, never below zero. */
    private fun reach(model: HandleModel.Reach): CodeBlock =
        CodeBlock.builder()
            .addStatement("val origin = target.origin")
            .addStatement("val value0 = target.component.%N", model.field)
            .beginControlFlow(
                "handle(%T(origin.x + value0, origin.y, origin.z), %L, %T.Along(%T.X)) { drag ->",
                EditorNames.WORLD_POINT,
                when (model.kind) {
                    ReachKind.Radius -> CodeBlock.of("%T.Point", EditorNames.HANDLE_SHAPE)
                    ReachKind.Range -> CodeBlock.of("%T.Line(origin)", EditorNames.HANDLE_SHAPE)
                },
                EditorNames.DRAG_CONSTRAINT,
                EditorNames.AXIS,
            )
            .addStatement("write(%T::%N, maxOf(0f, value0 + drag.stretchFrom(origin)))", model.component, model.field)
            .endControlFlow()
            .build()

    private fun sphere(): CodeBlock = CodeBlock.of("%T.Sphere", EditorNames.HANDLE_SHAPE)

    /** Across the ground plane in 2D; across the plane facing the view in 3D. */
    private fun constraint(threeD: Boolean): CodeBlock =
        if (threeD) {
            CodeBlock.of("%T.ViewPlane", EditorNames.DRAG_CONSTRAINT)
        } else {
            CodeBlock.of("%T.Across(%T.XY)", EditorNames.DRAG_CONSTRAINT, EditorNames.PLANE)
        }

}
