package dev.wildware.udea.codegen.gizmo

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STAR
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.joinToCode
import dev.wildware.udea.codegen.registry.RegistryEmitter

/**
 * Emits one `Gizmo` object per handle annotation, and a game's `<Game>GizmoRegistry` (issue #233).
 *
 * A generated gizmo is written exactly as a person would write it against the public API, which is
 * the point: an annotation is shorthand, and `GeneratedGizmoTest` holds each kind to a hand-written
 * twin. A handle is one call to the editor's built-in for it - `moveHandles`, `sizeHandles`,
 * `rotationHandle`, `radiusHandle`, `rangeHandle` in 2D (issue #236), and `translateHandles`,
 * `rotationRings`, `scaleHandles` in 3D (issue #237) - the public functions a hand-written gizmo
 * calls too, so a generated gizmo and a built-in cannot differ. A 3D size is the one handle still
 * written out here, as issue #233 wrote it: the editor has no built-in 3D resize.
 * Every field is read by direct property access and named by a property reference, so nothing is
 * looked up by name at run time, and the whole file is KotlinPoet.
 *
 * Every drag response computes a change from what [build] read when it declared the handle, because
 * the editor keeps the pressed handle for the whole drag while the drag itself changes the component.
 */
internal object GizmoEmitter {

    /** The file holding [model]'s gizmo. */
    fun emit(model: HandleModel): FileSpec {
        val component = model.component
        val gizmo = TypeSpec.objectBuilder(model.gizmo)
            .addModifiers(KModifier.INTERNAL)
            .addSuperinterface(EditorNames.GIZMO_INTERFACE.parameterizedBy(component))
            .addKdoc(
                "The gizmo `@%L` declares on [%T]. Generated by udea-codegen: edit the annotation, not this.\n",
                model.annotation,
                component,
            )
            .addProperty(
                PropertySpec.builder("component", EditorNames.COMPONENT_TYPE.parameterizedBy(component), KModifier.OVERRIDE)
                    .initializer("%T", component)
                    .build(),
            )
            .addFunction(
                FunSpec.builder("build")
                    .addModifiers(KModifier.OVERRIDE)
                    .receiver(EditorNames.GIZMO_SCOPE.parameterizedBy(component))
                    .addParameter("target", EditorNames.GIZMO_TARGET.parameterizedBy(component))
                    .addCode(body(model))
                    .build(),
            )
            .build()
        return FileSpec.builder(model.gizmo.packageName, model.gizmo.simpleName)
            .addFileComment("Generated by udea-codegen from @%L on %L.\nDo not edit.", model.annotation, component.canonicalName)
            .addType(gizmo)
            .build()
    }

    /**
     * `internal object <Game>GizmoRegistry : GizmoRegistry`, listing [gizmos] - each already an
     * expression, an object as itself or a class constructed - in the order given.
     */
    fun registry(name: ClassName, game: String, gizmos: List<CodeBlock>): FileSpec =
        FileSpec.builder(name.packageName, name.simpleName)
            .addFileComment("Generated by udea-codegen for %L's editor.\nDo not edit.", game)
            .addType(
                TypeSpec.objectBuilder(name)
                    .addModifiers(KModifier.INTERNAL)
                    .addSuperinterface(EditorNames.GIZMO_REGISTRY)
                    .addKdoc(
                        "Every gizmo %L's editor offers: one per handle annotation on its components, " +
                            "and every hand-written Gizmo in its editor source set.\n",
                        game,
                    )
                    .addProperty(
                        PropertySpec.builder(
                            "gizmos",
                            LIST.parameterizedBy(EditorNames.GIZMO_INTERFACE.parameterizedBy(STAR)),
                            KModifier.OVERRIDE,
                        )
                            .addKdoc("Every gizmo, in ascending fully-qualified class-name order.")
                            .initializer(RegistryEmitter.listInitializer(gizmos))
                            .build(),
                    )
                    .build(),
            )
            .build()

    private fun body(model: HandleModel): CodeBlock = when (model) {
        is HandleModel.Position -> position(model)
        is HandleModel.Size -> size(model)
        is HandleModel.Rotation -> rotation(model)
        is HandleModel.Scale -> builtin(EditorNames.SCALE_HANDLES, model.component, model.x, model.y, model.z)
        is HandleModel.Reach -> reach(model)
    }

    /** At the fields' point; moved by the drag. The built-in move on the ground plane in 2D; the built-in translate in 3D. */
    private fun position(model: HandleModel.Position): CodeBlock {
        val z = model.z ?: return builtin(EditorNames.MOVE_HANDLES, model.component, model.x, model.y)
        return builtin(EditorNames.TRANSLATE_HANDLES, model.component, model.x, model.y, z)
    }

    /**
     * A size centred on the entity; the size follows a corner, never below zero. The built-in's corners
     * and sides in 2D; one corner dragged in the view's plane in 3D.
     */
    private fun size(model: HandleModel.Size): CodeBlock {
        val c = model.component
        val depth = model.depth ?: return builtin(EditorNames.SIZE_HANDLES, c, model.width, model.height)
        return CodeBlock.builder()
            .addStatement("val origin = target.origin")
            .addStatement("val width0 = target.component.%N", model.width)
            .addStatement("val height0 = target.component.%N", model.height)
            .addStatement("val depth0 = target.component.%N", depth)
            .beginControlFlow(
                "handle(%T(origin.x + width0 / 2f, origin.y + height0 / 2f, origin.z + depth0 / 2f), %T.BoxCorner, %L) { drag ->",
                EditorNames.WORLD_POINT,
                EditorNames.HANDLE_SHAPE,
                viewPlane(),
            )
            .addStatement("write(%T::%N, maxOf(0f, width0 + drag.spread(%T.X, origin)))", c, model.width, EditorNames.AXIS)
            .addStatement("write(%T::%N, maxOf(0f, height0 + drag.spread(%T.Y, origin)))", c, model.height, EditorNames.AXIS)
            .addStatement("write(%T::%N, maxOf(0f, depth0 + drag.spread(%T.Z, origin)))", c, depth, EditorNames.AXIS)
            .endControlFlow()
            .build()
    }

    /** A ring about the up axis at the entity, or one per angle in 3D: the built-in either way. */
    private fun rotation(model: HandleModel.Rotation): CodeBlock {
        val aboutX = model.aboutX
        val aboutY = model.aboutY
        if (aboutX == null || aboutY == null) return builtin(EditorNames.ROTATION_HANDLE, model.component, model.field)
        return builtin(EditorNames.ROTATION_RINGS, model.component, aboutX, aboutY, model.field)
    }

    /** A grip on the rim of a circle of the field's size: the built-in for its kind. */
    private fun reach(model: HandleModel.Reach): CodeBlock =
        builtin(model.kind.builtin, model.component, model.field)

    /**
     * One call to a built-in, `builtin(target, C::a, target.component.a, ...)`: each field named by a
     * reference for its write, and read directly for where the handles go.
     */
    private fun builtin(function: MemberName, component: ClassName, vararg fields: String): CodeBlock {
        val arguments = fields.map { field -> CodeBlock.of("%T::%N, target.component.%N", component, field, field) }
        return CodeBlock.builder()
            .addStatement("%M(target, %L)", function, arguments.joinToCode())
            .build()
    }

    /** Across the plane facing the view: a free drag in 3D. */
    private fun viewPlane(): CodeBlock = CodeBlock.of("%T.ViewPlane", EditorNames.DRAG_CONSTRAINT)

}
