package dev.wildware.udea.codegen.rpc

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import dev.wildware.udea.codegen.CoreNames

/**
 * Turns an [RpcFunction] into the `RpcDescriptor` object for it: the codec, the typed send
 * function, and **the authority guard**.
 *
 * ## The guard is the reason this file exists
 *
 * The old engine's ability path was `AbilityPacket(entityId, abilityIndex)` read off the wire,
 * resolved to an entity and fired, with `PacketUtil.kt:148` carrying the literal comment
 * `// TODO validate the sender!`. Any client could fire any ability on any entity - the enemy
 * team's ultimates included - and the build was green, because "remember to check the sender"
 * is not a thing a compiler can be asked about.
 *
 * Here it is not remembered. [receive] is the only path from a datagram to the annotated
 * function, and [ownershipGuard] emits the check into it from the declared
 * `@Rpc(authority = ...)`. There is no branch that reaches the call without passing it, no
 * flag that disables it and no way to write an ownership-gated RPC whose guard was left out:
 * `RpcModelBuilder` fails the build for a declaration that has nothing to check.
 *
 * KotlinPoet, never string building, for the reason `ReplicatorEmitter` gives. Emission is
 * total: every question that could fail was answered while the model was built.
 */
internal object RpcEmitter {

    private const val RPC = "dev.wildware.udea.net.rpc"
    private const val TRANSPORT = "dev.wildware.udea.net.transport"
    private const val WIRE = "dev.wildware.udea.net.wire"
    private const val BITS = "dev.wildware.udea.net.bits"

    private val RPC_DESCRIPTOR = ClassName(RPC, "RpcDescriptor")
    private val RPC_DIRECTION = ClassName(RPC, "RpcDirection")
    private val RPC_RELIABILITY = ClassName(RPC, "RpcReliability")
    private val RPC_RELEVANCY = ClassName(RPC, "RpcRelevancy")
    private val RPC_RATE = ClassName(RPC, "RpcRate")
    private val RPC_REFUSAL = ClassName(RPC, "RpcRefusal")
    private val RPC_OWNERSHIP = ClassName(RPC, "RpcOwnership")
    private val RPC_OUTBOX = ClassName(RPC, "RpcOutbox")
    private val PEER_ID = ClassName(TRANSPORT, "PeerId")
    private val FRAME_WRITER = ClassName(WIRE, "FrameWriter")
    private val MALFORMED = ClassName(BITS, "MalformedBitStream")
    private val AUTHORITY = ClassName("dev.wildware.udea.annotations", "Authority")

    fun emit(rpc: RpcFunction): FileSpec = FileSpec.builder(rpc.packageName, rpc.objectName)
        .addFileComment("Generated by udea-codegen from @Rpc %L.\nDo not edit.", rpc.qualifiedName)
        .addType(descriptorObject(rpc))
        .build()

    private fun descriptorObject(rpc: RpcFunction): TypeSpec {
        val builder = TypeSpec.objectBuilder(rpc.objectName)
            .addModifiers(KModifier.PUBLIC)
            .addKdoc(kdoc(rpc))
            .addSuperinterface(RPC_DESCRIPTOR)

        builder.addProperty(
            PropertySpec.builder("name", STRING, KModifier.OVERRIDE)
                .initializer("%S", rpc.qualifiedName)
                .build(),
        )
        builder.addProperty(constant("direction", RPC_DIRECTION, rpc.direction))
        builder.addProperty(constant("authority", AUTHORITY, rpc.authority))
        builder.addProperty(constant("reliability", RPC_RELIABILITY, rpc.reliability))
        builder.addProperty(constant("relevancy", RPC_RELEVANCY, rpc.relevancy))
        builder.addProperty(
            PropertySpec.builder("rate", RPC_RATE, KModifier.OVERRIDE)
                .addKdoc(
                    "From `@Rpc(ratePerSecond = %L, burst = %L)`. Enforced in ticks by " +
                        "`RpcRateLimiter`, never in wall time.",
                    rpc.ratePerSecond,
                    rpc.burst,
                )
                .initializer(
                    "%T(perSecond = %L, burst = %L)",
                    RPC_RATE,
                    rpc.ratePerSecond,
                    rpc.burst,
                )
                .build(),
        )
        builder.addFunction(send(rpc))
        builder.addFunction(receive(rpc))
        return builder.build()
    }

    private fun constant(name: String, type: ClassName, value: String): PropertySpec =
        PropertySpec.builder(name, type, KModifier.OVERRIDE)
            .initializer("%T.%L", type, value)
            .build()

    /**
     * The typed half of the surface: an ordinary Kotlin call, with the argument types the
     * declaration wrote, that produces the bytes [receive] reads.
     *
     * The client never builds a payload by hand, which is what kept the two halves of the old
     * codec able to disagree: `packets.kt` wrote a fixed 2048-byte buffer with a hand-rolled
     * layout at one end and parsed it at the other.
     */
    private fun send(rpc: RpcFunction): FunSpec {
        val builder = FunSpec.builder("send")
            .addModifiers(KModifier.PUBLIC)
            .addKdoc(
                "Writes one call to %L into [frames].\n\nThe client sends this and nothing " +
                    "else: an RPC payload is these arguments, never component state.\n",
                rpc.functionName,
            )
            .addParameter("frames", FRAME_WRITER)
            .addParameter("outbox", RPC_OUTBOX)
            .returns(UNIT)
        for (arg in rpc.args) builder.addParameter(arg.name, arg.type)
        val body = CodeBlock.builder().addStatement("val out = outbox.open(frames, this)")
        for (arg in rpc.args) body.add(write(arg))
        body.addStatement("outbox.close(frames)")
        return builder.addCode(body.build()).build()
    }

    private fun write(arg: RpcArg): CodeBlock = when (arg.kind) {
        RpcArgKind.BOOLEAN -> CodeBlock.of("out.writeBoolean(%N)\n", arg.name)
        RpcArgKind.INT -> CodeBlock.of("out.writeInt(%N)\n", arg.name)
        RpcArgKind.LONG -> CodeBlock.of("out.writeLong(%N)\n", arg.name)
        RpcArgKind.FLOAT -> CodeBlock.of("out.writeFloat(%N)\n", arg.name)
        RpcArgKind.ENUM -> CodeBlock.of("out.writeInt(%N.ordinal)\n", arg.name)
        RpcArgKind.NET_ID -> CodeBlock.of("out.writeInt(%N.raw)\n", arg.name)
        RpcArgKind.TICK -> CodeBlock.of("out.writeLong(%N.value)\n", arg.name)
    }

    /**
     * Decode, guard, invoke - in that order, with nothing between the guard and the call.
     *
     * The arguments are read first because the entity the guard is about is one of them. The
     * read itself is total over hostile input: `NetId.ofRaw` rejects a reserved-bit pattern and
     * an out-of-range enum ordinal raises `MalformedBitStream` rather than indexing past the
     * end of `entries`, which is the containment the frame's length prefix cannot provide on
     * its own.
     */
    private fun receive(rpc: RpcFunction): FunSpec {
        val body = CodeBlock.builder()
        if (rpc.target == null) {
            // Nothing is read and nothing is called. A server-only RPC replayed at the server
            // by a client is refused *before* its arguments are decoded, which is both the
            // cheaper answer under a flood and the only one that leaves no unreachable
            // invocation in the generated file for `-Werror` to reject.
            return receiveBuilder(rpc).addCode(ownershipGuard(rpc)).build()
        }
        for (arg in rpc.args) body.add(read(arg))
        body.add(ownershipGuard(rpc))
        val call = CodeBlock.builder()
            .add("%M(", MemberName(rpc.packageName, rpc.functionName))
            .apply {
                rpc.args.forEachIndexed { position, arg ->
                    if (position > 0) add(", ")
                    add("%N", arg.name)
                }
            }
            .add(")\n")
            .build()
        body.add(call)
        body.addStatement("return null")
        return receiveBuilder(rpc).addCode(body.build()).build()
    }

    /**
     * The `receive` signature, shared by both bodies.
     *
     * A server-only descriptor uses none of its three parameters, so each is suppressed rather
     * than renamed: the signature is an override and cannot change, and a leading underscore
     * would make the one member every reviewer looks at read as scaffolding.
     */
    private fun receiveBuilder(rpc: RpcFunction): FunSpec.Builder {
        val builder = FunSpec.builder("receive")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("sender", PEER_ID)
            .addParameter("ownership", RPC_OWNERSHIP)
            .addParameter("src", CoreNames.BIT_READER)
            .returns(RPC_REFUSAL.copy(nullable = true))
        if (rpc.target == null) builder.addAnnotation(unusedParameterSuppression())
        return builder
    }

    private fun unusedParameterSuppression() = com.squareup.kotlinpoet.AnnotationSpec
        .builder(Suppress::class)
        .addMember("%S", "UNUSED_PARAMETER")
        .build()

    private fun read(arg: RpcArg): CodeBlock = when (arg.kind) {
        RpcArgKind.BOOLEAN -> CodeBlock.of("val %N = src.readBoolean()\n", arg.name)
        RpcArgKind.INT -> CodeBlock.of("val %N = src.readInt()\n", arg.name)
        RpcArgKind.LONG -> CodeBlock.of("val %N = src.readLong()\n", arg.name)
        RpcArgKind.FLOAT -> CodeBlock.of("val %N = src.readFloat()\n", arg.name)
        RpcArgKind.NET_ID -> CodeBlock.of("val %N = %T.ofRaw(src.readInt())\n", arg.name, CoreNames.NET_ID)
        RpcArgKind.TICK -> CodeBlock.of("val %N = %T(src.readLong())\n", arg.name, CoreNames.TICK)
        RpcArgKind.ENUM -> enumRead(arg)
    }

    /**
     * An enum argument, read as its ordinal and **bounds checked**.
     *
     * `entries[ordinal]` on an unchecked remote integer is an `ArrayIndexOutOfBoundsException`
     * thrown from inside a decode loop, which is a crash a peer chooses. The frame length
     * prefix contains a malformed *stream*; it cannot contain a well-formed stream carrying a
     * number that has no meaning.
     */
    private fun enumRead(arg: RpcArg): CodeBlock {
        val entries = requireNotNull(arg.enumEntries)
        val ordinal = arg.name + "Ordinal"
        return CodeBlock.builder()
            .addStatement("val %L = src.readInt()", ordinal)
            .beginControlFlow("if (%L !in %T.entries.indices)", ordinal, entries)
            .addStatement(
                "throw %T(%S + %L)",
                MALFORMED,
                "not an ordinal of ${entries.simpleName}: ",
                ordinal,
            )
            .endControlFlow()
            .addStatement("val %N = %T.entries[%L]", arg.name, entries, ordinal)
            .build()
    }

    /**
     * The generated authority check, emitted from `@Rpc(authority = ...)`.
     *
     * `Server` emits an unconditional refusal - reachable only for a server-originated RPC a
     * client replayed, because `RpcModelBuilder` refuses a client-to-server call declared that
     * way. Both ownership authorities emit the same comparison: the connection that sent the
     * datagram against the connection that owns the entity named in it. `RpcOwnership` answers
     * `PeerId.SERVER` for an entity no client owns, so an AI unit and another player's champion
     * refuse identically rather than one of them falling through.
     */
    private fun ownershipGuard(rpc: RpcFunction): CodeBlock {
        val target = rpc.target
        if (target == null) {
            return CodeBlock.builder()
                .add("// Generated from @Rpc(authority = %L): no client may invoke this.\n", rpc.authority)
                .addStatement(
                    "return %T.ServerOnly(name, %T.%L, sender)",
                    RPC_REFUSAL,
                    AUTHORITY,
                    rpc.authority,
                )
                .build()
        }
        return CodeBlock.builder()
            .add("// Generated from @Rpc(authority = %L). Not optional and not overridable:\n", rpc.authority)
            .add("// this is the check PacketUtil.kt:148 left as a TODO.\n")
            .addStatement("val owner = ownership.ownerOf(%N)", target.name)
            .beginControlFlow("if (owner != sender)")
            .addStatement(
                "return %T.NotOwner(name, %T.%L, sender, %N, owner)",
                RPC_REFUSAL,
                AUTHORITY,
                rpc.authority,
                target.name,
            )
            .endControlFlow()
            .build()
    }

    private fun kdoc(rpc: RpcFunction): CodeBlock {
        val doc = CodeBlock.builder()
            .add("Generated `RpcDescriptor` for `%L`.\n\n", rpc.qualifiedName)
            .add("| declaration | value |\n|---|---|\n")
            .add("| direction | `%L` |\n", rpc.direction)
            .add("| authority | `%L` |\n", rpc.authority)
            .add("| reliability | `%L` |\n", rpc.reliability)
            .add("| relevancy | `%L` |\n", rpc.relevancy)
            .add("| rate | `%L`/s, burst `%L` |\n", rpc.ratePerSecond, rpc.burst)
            .add("\n")
        val target = rpc.target
        if (target == null) {
            doc.add("No client may invoke this: the guard refuses every sender.\n")
        } else {
            doc.add(
                "The sender must own `%L`, or `receive` returns `RpcRefusal.NotOwner` and the\n" +
                    "function below is never called.\n",
                target.name,
            )
        }
        return doc.build()
    }
}
